# Generated by Django 6.0.4 on 2026-07-18 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TallerReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=10)),
                ('taller_slug', models.CharField(choices=[('taller1-terapeutas', 'Seña — Taller Terapeutas 1-ago (resto se paga presencial)')], max_length=40)),
                ('amount_local', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='fractonespack',
            new_name='payments_fr_gateway_1ed085_idx',
            old_name='payments_fp_gateway_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='payments_su_gateway_4725d6_idx',
            old_name='payments_su_gateway_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='payments_su_user_id_058311_idx',
            old_name='payments_su_user_status_idx',
        ),
        migrations.AlterField(
            model_name='fractonespack',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='tallerreserva',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tallerreserva',
            index=models.Index(fields=['gateway', 'gateway_payment_id'], name='payments_ta_gateway_4ac347_idx'),
        ),
    ]
