# Generated by Django 6.0.4 on 2026-07-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_tallerreserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractonespack',
            name='pack_slug',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tallerreserva',
            name='taller_slug',
            field=models.CharField(choices=[('taller1-terapeutas', 'Seña — Taller Terapeutas 1-ago (reserva de cupo)')], max_length=40),
        ),
    ]
