# Generated by Django 6.0.4 on 2026-08-19 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_fractonespack_pack_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('herida', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('nuevo', 'Nuevo'), ('pdf_entregado', 'PDF entregado'), ('contactado', 'Contactado'), ('comprado', 'Comprado')], default='nuevo', max_length=20)),
                ('canal_origen', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EbookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_slug', models.CharField(choices=[('endonautica-ebook', 'Ebook Endonautica')], default='endonautica-ebook', max_length=40)),
                ('gateway', models.CharField(choices=[('paypal', 'PayPal'), ('mp', 'MercadoPago')], max_length=10)),
                ('amount_local', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('delivered', 'Entregado')], default='pending', max_length=20)),
                ('canal_origen', models.CharField(blank=True, max_length=40)),
                ('download_token', models.CharField(blank=True, max_length=64)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebook_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gateway', 'gateway_payment_id'], name='payments_eb_gateway_fe8d8e_idx'), models.Index(fields=['download_token'], name='payments_eb_downloa_c191c2_idx')],
            },
        ),
    ]
