# Generated by Django 6.0.4 on 2026-08-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_ebooklead_ebookorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EbookFunnelEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('step', models.CharField(choices=[('T2', 'Test · ciclo de control (+2d)'), ('T3', 'Test · inercia e invitación (+4d)'), ('A1', 'Carrito · a la hora'), ('A2', 'Carrito · a las 24 h'), ('P2', 'Post-compra · resistencia (+3d)'), ('P3', 'Post-compra · el mapa no es el territorio (+7d)')], max_length=2)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('email', 'step'), name='funnel_email_una_vez_por_paso')],
            },
        ),
    ]
