# Generated by Django 6.0.4 on 2026-10-09 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_ebookoptout_ebookfunnelemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadConsultoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'disponibilidad de consultoría',
                'verbose_name_plural': 'disponibilidad de consultoría',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.AlterField(
            model_name='ebookorder',
            name='product_slug',
            field=models.CharField(choices=[('endonautica-ebook', 'Ebook Endonautica'), ('consultoria-60', 'Consultoría Endonautas (60 min)')], default='endonautica-ebook', max_length=40),
        ),
        migrations.CreateModel(
            name='ConsultoriaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('duracion_min', models.PositiveSmallIntegerField(default=60)),
                ('amount_local', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('gateway', models.CharField(default='mp', max_length=10)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pago pendiente'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('motivo', models.TextField(blank=True, help_text='Qué quiere trabajar (lo escribe al reservar).')),
                ('canal_origen', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inicio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'paid')), fields=('inicio',), name='consultoria_un_pago_por_horario')],
            },
        ),
    ]
