from django.core.management.base import BaseCommand
from mirror.models import EjercicioRegulacion


EJERCICIOS = [
    # ── ALIENTO ─────────────────────────────────────────────────────────────
    {
        'title': 'Nadi Shodhana',
        'subtitle': 'Fosas nasales alternas',
        'description': 'Equilibra los hemisferios cerebrales y calma la mente al alternar el flujo de aire entre fosas.',
        'instructions': 'Siéntate con la espalda recta. Usa el pulgar derecho para tapar la fosa nasal derecha. Inhala por la izquierda, luego tapa ambas, destapa la derecha y exhala por ella. Repite alternando.',
        'category': 'aliento',
        'ui_mode': 'pasos',
        'duration_minutes': 3,
        'steps': [
            {'title': 'Posición', 'body': 'Siéntate con espalda recta. Pulgar derecho listo para tapar la fosa nasal derecha; anular derecho para la izquierda.'},
            {'title': 'Inhala por la izquierda', 'body': 'Tapa la fosa derecha con el pulgar. Inhala profunda y lentamente por la fosa nasal izquierda.'},
            {'title': 'Retención', 'body': 'Tapa ambas fosas. Sostén el aire un instante.'},
            {'title': 'Exhala por la derecha', 'body': 'Destapa la fosa nasal derecha. Exhala lentamente por ahí.'},
            {'title': 'Inhala por la derecha', 'body': 'Mantén tapada la fosa izquierda. Inhala por la derecha.'},
            {'title': 'Cierra y exhala por la izquierda', 'body': 'Tapa la derecha, destapa la izquierda. Exhala. Esto completa un ciclo. Repite 5-10 veces.'},
        ],
        'emotional_targets': ['ansiedad', 'confusion', 'estres'],
        'body_zones': ['cabeza', 'garganta'],
        'precaution': '',
        'order': 1,
    },
    {
        'title': 'Respiración de Fuego',
        'subtitle': 'Kapalabhati',
        'description': 'Despierta la energía, oxigena el cuerpo y limpia toxinas mediante exhalaciones rítmicas y vigorosas.',
        'instructions': 'Inhala y exhala por la nariz de manera rápida y continua. El enfoque está en la exhalación: contrae el ombligo hacia la columna con cada exhalación. La inhalación es pasiva y natural.',
        'category': 'aliento',
        'ui_mode': 'respiracion',
        'duration_minutes': 2,
        'phases': [
            {'name': 'Exhala-contrae', 'duration': 1, 'cue': 'Contrae el ombligo hacia la columna'},
            {'name': 'Inhala-suelta', 'duration': 1, 'cue': 'Suelta y deja que el aire entre solo'},
        ],
        'emotional_targets': ['agotamiento', 'bloqueo'],
        'body_zones': ['diafragma', 'abdomen'],
        'precaution': 'No realizar en embarazo ni con presión arterial alta sin control médico.',
        'order': 2,
    },
    {
        'title': 'Respiración Cuadrada',
        'subtitle': '4 · 4 · 4 · 4 — Equilibrio y enfoque',
        'description': 'Cuatro tiempos iguales que llevan al sistema nervioso a un estado de equilibrio y concentración.',
        'instructions': 'Inhala 4 tiempos, sostén 4, exhala 4, sostén sin aire 4. Repite el ciclo entre 5 y 10 veces.',
        'category': 'aliento',
        'ui_mode': 'respiracion',
        'duration_minutes': 4,
        'phases': [
            {'name': 'Inhala', 'duration': 4, 'cue': 'Llena el abdomen primero, luego el pecho'},
            {'name': 'Retén', 'duration': 4, 'cue': 'Sostén sin tensión'},
            {'name': 'Exhala', 'duration': 4, 'cue': 'Vacía el pecho primero, luego el abdomen'},
            {'name': 'Vacío', 'duration': 4, 'cue': 'Sin aire, sin tensión'},
        ],
        'emotional_targets': ['ansiedad', 'estres', 'confusion'],
        'body_zones': ['pecho', 'diafragma'],
        'precaution': '',
        'order': 3,
    },
    {
        'title': 'Parasimpático 4 · 8',
        'subtitle': 'Activa el freno del sistema nervioso',
        'description': 'La exhalación doble activa el nervio vago y el sistema parasimpático. Ideal para ansiedad e insomnio.',
        'instructions': 'Inhala profundamente contando hasta 4. Exhala muy lentamente contando hasta 8. Repite entre 5 y 10 veces.',
        'category': 'aliento',
        'ui_mode': 'respiracion',
        'duration_minutes': 3,
        'phases': [
            {'name': 'Inhala', 'duration': 4, 'cue': 'Lenta y profunda por la nariz'},
            {'name': 'Exhala', 'duration': 8, 'cue': 'Muy lentamente, por la boca entreabierta'},
        ],
        'emotional_targets': ['ansiedad', 'miedo', 'agotamiento'],
        'body_zones': ['pecho', 'garganta'],
        'precaution': '',
        'order': 4,
    },
    {
        'title': 'Simpático 8 · 4',
        'subtitle': 'Activa el sistema de alerta',
        'description': 'La inhalación larga carga energía; la exhalación vigorosa despierta y activa. Para el cansancio o la apatía.',
        'instructions': 'Inhala de forma pausada contando hasta 8. Exhala de forma rápida y vigorosa contando hasta 4. Repite entre 5 y 8 veces.',
        'category': 'aliento',
        'ui_mode': 'respiracion',
        'duration_minutes': 3,
        'phases': [
            {'name': 'Inhala', 'duration': 8, 'cue': 'Pausada, llenando completamente'},
            {'name': 'Exhala', 'duration': 4, 'cue': 'Vigorosa y rápida por la nariz'},
        ],
        'emotional_targets': ['agotamiento', 'bloqueo'],
        'body_zones': ['pecho', 'diafragma'],
        'precaution': '',
        'order': 5,
    },
    {
        'title': 'Suspiro de Purificación',
        'subtitle': 'Liberación catártica inmediata',
        'description': 'Una inhalación máxima seguida de una exhalación sonora libera tensión acumulada en segundos.',
        'instructions': 'Toma la inhalación más profunda que puedas por la nariz. Al exhalar, abre la boca y suelta el aire de golpe con un "¡Haaa!" sonoro. Repite 3 veces.',
        'category': 'aliento',
        'ui_mode': 'pasos',
        'duration_minutes': 1,
        'steps': [
            {'title': 'Prepárate', 'body': 'De pie o sentado, afloja los hombros.'},
            {'title': 'Inhala al máximo', 'body': 'Toma la inhalación más profunda que puedas, llenando pulmones y abdomen hasta el límite.'},
            {'title': 'Exhala con sonido', 'body': 'Abre la boca y suelta todo el aire de golpe con un "¡HAAA!" sonoro y libre. Sin contener.'},
            {'title': 'Repite', 'body': 'Vuelve a inhalar naturalmente y repite el ciclo 2 veces más. Total: 3 purificaciones.'},
        ],
        'emotional_targets': ['ira', 'estres', 'bloqueo', 'tristeza'],
        'body_zones': ['pecho', 'garganta', 'diafragma'],
        'precaution': '',
        'order': 6,
    },
    {
        'title': 'Respiración Conectada',
        'subtitle': 'Flujo circular sin pausa',
        'description': 'Elimina la pausa entre inhalación y exhalación para crear un flujo continuo que procesa bloqueos profundos.',
        'instructions': 'Respira por la nariz o la boca, eliminando la pausa natural entre cada ciclo. En cuanto terminas de inhalar, comienzas a exhalar; en cuanto terminas de exhalar, comienzas a inhalar. Círculo continuo.',
        'category': 'aliento',
        'ui_mode': 'respiracion',
        'duration_minutes': 5,
        'phases': [
            {'name': 'Inhala', 'duration': 3, 'cue': 'Sin pausa al final — fluye directo a la exhalación'},
            {'name': 'Exhala', 'duration': 3, 'cue': 'Sin pausa al final — fluye directo a la inhalación'},
        ],
        'emotional_targets': ['bloqueo', 'tristeza', 'agotamiento'],
        'body_zones': ['pecho', 'diafragma', 'abdomen'],
        'precaution': 'Pueden surgir sensaciones intensas o emociones. Estás en un espacio seguro. Si sientes mareo, vuelve a una respiración normal.',
        'order': 7,
    },

    # ── INTEGRACIÓN ──────────────────────────────────────────────────────────
    {
        'title': 'Marcha Cruzada',
        'subtitle': 'Cross-Crawl — Coordinación interhemisférica',
        'description': 'El movimiento cruzado activa simultáneamente ambos hemisferios cerebrales y mejora la integración neurológica.',
        'instructions': 'De pie, lleva la rodilla izquierda y toca con el codo o mano derecha. Luego rodilla derecha con brazo izquierdo. Alterna rítmicamente durante 1-2 minutos.',
        'category': 'integracion',
        'ui_mode': 'pasos',
        'duration_minutes': 2,
        'steps': [
            {'title': 'Posición inicial', 'body': 'De pie, con espacio para moverte. Pies al ancho de los hombros.'},
            {'title': 'Marcha básica', 'body': 'Levanta la rodilla IZQUIERDA y tócala con la mano o codo DERECHO. Luego rodilla DERECHA con brazo IZQUIERDO. Alterna 30 veces.'},
            {'title': 'Variante con talón', 'body': 'Ahora toca el talón izquierdo por detrás con la mano derecha, y vice versa. 20 repeticiones.'},
            {'title': 'Con ojos cerrados', 'body': 'Repite la marcha básica pero con ojos cerrados. 20 repeticiones. Esto desafía y profundiza la integración.'},
        ],
        'emotional_targets': ['confusion', 'bloqueo', 'estres'],
        'body_zones': ['cabeza', 'extremidades'],
        'precaution': '',
        'order': 1,
    },
    {
        'title': '8 Perezoso',
        'subtitle': 'Movimientos oculares — Infinito',
        'description': 'Trazar el símbolo del infinito con los ojos integra los campos visuales y desbloquea memorias almacenadas.',
        'instructions': 'Extiende el pulgar frente a ti. Dibuja un 8 acostado grande en el aire. Mantén la cabeza quieta y sigue el pulgar solo con los ojos.',
        'category': 'integracion',
        'ui_mode': 'pasos',
        'duration_minutes': 2,
        'steps': [
            {'title': 'Prepara el pulgar', 'body': 'Extiende el brazo derecho con el pulgar hacia arriba, al centro del campo visual.'},
            {'title': 'Traza el infinito', 'body': 'Mueve el pulgar trazando un símbolo ∞ grande y fluido. Los ojos siguen al pulgar; la cabeza no se mueve. Hazlo lento y amplio. 10 repeticiones.'},
            {'title': 'Cambia de mano', 'body': 'Repite el mismo trazo con el pulgar izquierdo. 10 repeticiones.'},
            {'title': 'Ambas manos juntas', 'body': 'Une los pulgares y traza el infinito con ambas manos juntas. 10 repeticiones.'},
        ],
        'emotional_targets': ['confusion', 'bloqueo', 'ansiedad'],
        'body_zones': ['cabeza'],
        'precaution': '',
        'order': 2,
    },
    {
        'title': 'Ganchos de Cook',
        'subtitle': 'Hook-ups — Integración total',
        'description': 'La postura cruzada de extremidades crea un circuito que equilibra el campo eléctrico del cuerpo y calma el sistema nervioso profundamente.',
        'instructions': 'Paso 1: Cruza tobillo derecho sobre izquierdo y muñeca derecha sobre izquierda, entrelaza dedos y lleva manos al pecho. Cierra ojos, lengua al paladar. Paso 2: Descruza y une yemas de dedos frente al pecho.',
        'category': 'integracion',
        'ui_mode': 'pasos',
        'duration_minutes': 3,
        'steps': [
            {'title': 'Paso 1 — Cierre cruzado', 'body': 'Cruza el tobillo derecho sobre el izquierdo. Cruza la muñeca derecha sobre la izquierda, entrelaza los dedos y dobla los codos llevando las manos entrelazadas hacia tu pecho. Cierra los ojos, apoya la lengua en el paladar. Inhala profundo y sostén durante 1 minuto.'},
            {'title': 'Pausa de transición', 'body': 'Descruza piernas y brazos con calma. Nota la diferencia en tu cuerpo.'},
            {'title': 'Paso 2 — Carpa de dedos', 'body': 'Une las yemas de los dedos de ambas manos (formando una carpa o tienda) frente a tu pecho. No entrelaces los dedos. Respira profundo durante 30 segundos.'},
        ],
        'emotional_targets': ['ansiedad', 'estres', 'miedo', 'confusion'],
        'body_zones': ['cabeza', 'pecho', 'extremidades'],
        'precaution': '',
        'order': 3,
    },
    {
        'title': 'Botones del Cerebro',
        'subtitle': 'Activación subclavicular',
        'description': 'El masaje en los puntos bajo las clavículas mejora el flujo sanguíneo al cerebro y activa la conexión mente-cuerpo.',
        'instructions': 'Coloca una mano sobre el ombligo. Con la otra, usa pulgar e índice para masajear los huecos justo bajo las clavículas (a los lados del esternón). 30 segundos. Cambia de mano y repite.',
        'category': 'integracion',
        'ui_mode': 'pasos',
        'duration_minutes': 2,
        'steps': [
            {'title': 'Ancla el ombligo', 'body': 'Coloca la palma de una mano sobre el ombligo. Relaja el abdomen.'},
            {'title': 'Masajea los botones', 'body': 'Con la otra mano, localiza los dos huecos justo debajo de las clavículas, a ambos lados del esternón. Masajea firmemente con pulgar e índice durante 30 segundos.'},
            {'title': 'Cambia de mano', 'body': 'Intercambia las manos: ahora la mano que masajeaba va al ombligo, y la otra masajea los mismos puntos. 30 segundos más.'},
        ],
        'emotional_targets': ['confusion', 'agotamiento', 'bloqueo'],
        'body_zones': ['pecho', 'cabeza'],
        'precaution': '',
        'order': 4,
    },
    {
        'title': 'Tensión y Liberación',
        'subtitle': 'Isométrico — Descarga de estrés físico',
        'description': 'Contraer al máximo un grupo muscular para luego soltarlo de golpe libera el estrés físico acumulado con rapidez notable.',
        'instructions': 'Inhala y contrae al máximo un grupo muscular (puños, mandíbula, glúteos, o todo el cuerpo). Sostén 5 segundos. Exhala de golpe y suelta absolutamente todo.',
        'category': 'integracion',
        'ui_mode': 'pasos',
        'duration_minutes': 3,
        'steps': [
            {'title': 'Elige el grupo muscular', 'body': 'Decide si vas a contraer: los PUÑOS (ira/frustración), la MANDÍBULA (tensión crónica), los GLÚTEOS (estrés pélvico), o TODO EL CUERPO a la vez.'},
            {'title': 'Inhala y contrae', 'body': 'Inhala profundo. Al mismo tiempo, contrae el grupo elegido con la MÁXIMA fuerza posible. Sostén la tensión durante 5 segundos.'},
            {'title': 'Exhala y suelta', 'body': 'Exhala de golpe y suelta absolutamente todo. Siente el contraste: del máximo al cero. Observa la sensación de liberación.'},
            {'title': 'Repite', 'body': 'Descansa 10 segundos y repite 3 veces con el mismo grupo, o cambia a otro grupo muscular.'},
        ],
        'emotional_targets': ['ira', 'estres', 'bloqueo', 'agotamiento'],
        'body_zones': ['mandibula', 'pecho', 'abdomen', 'extremidades'],
        'precaution': '',
        'order': 5,
    },
    {
        'title': 'Rotación de Ojos',
        'subtitle': 'Reloj ocular — desbloqueo visual',
        'description': 'Mover los ojos en patrones sistemáticos desbloquea memorias y tensiones almacenadas en los campos visuales.',
        'instructions': 'Imagina un gran reloj frente a tu rostro. Sin mover la cabeza, lleva los ojos a las 12, las 3, las 6, las 9 y de vuelta a las 12. Luego en sentido contrario.',
        'category': 'integracion',
        'ui_mode': 'pasos',
        'duration_minutes': 2,
        'steps': [
            {'title': 'Centro', 'body': 'Cierra los ojos un momento. Al abrirlos, mira al frente, relajado.'},
            {'title': 'Sentido horario', 'body': 'Sin mover la cabeza: lleva los ojos a las 12, luego a las 3, luego a las 6, luego a las 9, y vuelve a las 12. Lento y amplio. 3 vueltas completas.'},
            {'title': 'Sentido antihorario', 'body': 'Ahora en sentido contrario: 12 → 9 → 6 → 3 → 12. Lento y amplio. 3 vueltas completas.'},
            {'title': 'Cierre', 'body': 'Cierra los ojos. Frota las palmas hasta generar calor y colócalas suavemente sobre los ojos cerrados. 30 segundos.'},
        ],
        'emotional_targets': ['bloqueo', 'confusion', 'estres'],
        'body_zones': ['cabeza'],
        'precaution': '',
        'order': 6,
    },

    # ── RESONANCIA ───────────────────────────────────────────────────────────
    {
        'title': 'Entonación de Vocales',
        'subtitle': 'Toning — Siete centros de energía',
        'description': 'Cada vocal resuena en una zona específica del cuerpo. La vibración del sonido propio regula la energía de cada centro.',
        'instructions': 'Siéntate cómodamente. Inhala profundo y al exhalar emite la vocal de forma constante y prolongada hasta quedarte sin aire. Visualiza la zona del cuerpo asociada.',
        'category': 'resonancia',
        'ui_mode': 'vocal',
        'duration_minutes': 7,
        'steps': [
            {'title': 'U — Base', 'body': 'Emite una "U" larga y grave. Siente la vibración en la base de la columna y en los pies. Enraizamiento.', 'zona': 'sacro'},
            {'title': 'O — Sacro', 'body': 'Emite una "O" larga y redonda. Dirige la vibración al bajo vientre y caderas. Fluidez.', 'zona': 'abdomen'},
            {'title': 'A — Plexo', 'body': 'Emite una "A" abierta y fuerte. Siente la vibración en el estómago. Poder y acción.', 'zona': 'plexo'},
            {'title': 'Ah — Corazón', 'body': 'Emite una "Ah" suspirada y amorosa. Dirige la vibración al pecho. Apertura y compasión.', 'zona': 'pecho'},
            {'title': 'E — Garganta', 'body': 'Emite una "E" larga y clara. Siente la vibración en el cuello y garganta. Expresión.', 'zona': 'garganta'},
            {'title': 'I — Tercer ojo', 'body': 'Emite una "I" aguda y enfocada. Dirige la vibración al entrecejo. Intuición y claridad.', 'zona': 'cabeza'},
            {'title': 'Mmm — Corona', 'body': 'Emite un "Mmm" vibrante o quédate en silencio absoluto. Siente la vibración en la cima de la cabeza. Conexión.', 'zona': 'cabeza'},
        ],
        'emotional_targets': ['bloqueo', 'estres', 'tristeza', 'desconexion'],
        'body_zones': ['garganta', 'pecho', 'abdomen', 'sacro', 'cabeza'],
        'precaution': '',
        'order': 1,
    },
    {
        'title': 'Seis Sonidos Curativos',
        'subtitle': 'Medicina China — Liberación emocional por órgano',
        'description': 'Cada órgano lleva una emoción. Estos seis sonidos liberan la emoción estancada y restauran el flujo de energía vital.',
        'instructions': 'Inhala llevando la atención al órgano específico. Al exhalar, emite el sonido suavemente (como un susurro fuerte) para liberar la emoción estancada.',
        'category': 'resonancia',
        'ui_mode': 'vocal',
        'duration_minutes': 6,
        'steps': [
            {'title': 'Hígado — Shhh', 'body': 'Pon la atención en el lado derecho bajo las costillas. Exhala emitiendo "Shhhh". Libera ira y frustración.', 'zona': 'abdomen'},
            {'title': 'Corazón — Haaa', 'body': 'Pon la atención en el pecho. Exhala emitiendo "Haaaa". Libera impaciencia y exceso de calor.', 'zona': 'pecho'},
            {'title': 'Bazo — Huuu', 'body': 'Pon la atención en el lado izquierdo bajo las costillas. Exhala emitiendo "Huuuu" desde la garganta. Libera preocupación y rumia.', 'zona': 'abdomen'},
            {'title': 'Pulmones — Ssss', 'body': 'Pon la atención en el pecho y hombros. Exhala emitiendo "Sssss" como serpiente. Libera tristeza y duelo.', 'zona': 'pecho'},
            {'title': 'Riñones — Chooo', 'body': 'Pon la atención en la zona lumbar. Exhala emitiendo "Choooo" como soplar una vela. Libera el miedo.', 'zona': 'espalda'},
            {'title': 'Triple Calentador — Hiiii', 'body': 'Acuéstate. Exhala emitiendo "Hiiii". Mientras suena, relaja todo el cuerpo de la cabeza a los pies. Equilibra temperatura y estrés.', 'zona': 'pecho'},
        ],
        'emotional_targets': ['ira', 'tristeza', 'miedo', 'ansiedad', 'estres'],
        'body_zones': ['pecho', 'abdomen', 'espalda'],
        'precaution': '',
        'order': 2,
    },
    {
        'title': 'Tarareo',
        'subtitle': 'Humming — Nervio vago y calma profunda',
        'description': 'El tarareo activa el nervio vago a través de la vibración en labios y cráneo, induciendo una calma profunda y rápida.',
        'instructions': 'Cierra la boca relajando la mandíbula (dientes separados). Inhala profundo por la nariz. Exhala emitiendo un "Mmmmmm" constante. Siente la vibración en labios, cara y cráneo.',
        'category': 'resonancia',
        'ui_mode': 'respiracion',
        'duration_minutes': 5,
        'phases': [
            {'name': 'Inhala', 'duration': 4, 'cue': 'Por la nariz, profundo y tranquilo'},
            {'name': 'Mmmmm', 'duration': 8, 'cue': 'Boca cerrada, labios relajados. Siente la vibración en el cráneo.'},
        ],
        'emotional_targets': ['ansiedad', 'estres', 'agotamiento', 'bloqueo'],
        'body_zones': ['garganta', 'cabeza', 'pecho'],
        'precaution': '',
        'order': 3,
    },

    # ── ESPECTRO ─────────────────────────────────────────────────────────────
    {
        'title': 'Respiración de Color',
        'subtitle': 'Frecuencia lumínica dirigida',
        'description': 'Inhalar un color específico y dirigirlo mentalmente hacia una zona del cuerpo reprograma la respuesta celular de esa zona.',
        'instructions': 'Cierra los ojos. Elige el color que el cuerpo necesita. Visualiza esa niebla a tu alrededor. Al inhalar, dirígela mentalmente al órgano o zona que necesita sanación.',
        'category': 'espectro',
        'ui_mode': 'visualizacion',
        'duration_minutes': 5,
        'steps': [
            {'title': 'Elige tu color', 'body': 'Cierra los ojos. Pregúntate intuitivamente: ¿qué color necesita mi cuerpo ahora? El primer color que aparezca es el correcto. No lo analices.'},
            {'title': 'La niebla de color', 'body': 'Visualiza una niebla o luz suave de ese color a tu alrededor. Deja que te envuelva completamente.'},
            {'title': 'Inhala el color', 'body': 'Al inhalar, imagina que respiras esa niebla de color. La diriges mentalmente hacia el órgano, la zona de tensión o el chakra que necesita atención.'},
            {'title': 'Exhala lo oscuro', 'body': 'Al exhalar, visualiza que expulsas energía turbia, gris o pesada. Con cada exhalación, la zona se aclara más.'},
            {'title': 'Saturación', 'body': 'Continúa por 5-10 respiraciones hasta que la zona se sienta saturada de ese color. Cierra el ejercicio con 3 respiraciones normales.'},
        ],
        'emotional_targets': ['bloqueo', 'tristeza', 'agotamiento', 'desconexion'],
        'body_zones': ['pecho', 'abdomen', 'cabeza'],
        'precaution': '',
        'order': 1,
    },
    {
        'title': 'Los 5 Elementos',
        'subtitle': 'Respiración elemental',
        'description': 'Cinco patrones distintos de respiración nariz-boca activan las energías de Tierra, Agua, Fuego, Aire y Éter.',
        'instructions': 'Realiza 5 a 10 respiraciones profundas según el patrón de cada elemento. Visualiza la cualidad de cada elemento mientras respiras.',
        'category': 'espectro',
        'ui_mode': 'pasos',
        'duration_minutes': 5,
        'steps': [
            {'title': 'Tierra — Arraigo', 'body': 'Inhala por la nariz / Exhala por la nariz. Siente tus pies firmes en el suelo. Imagina raíces. 5 respiraciones.'},
            {'title': 'Agua — Limpieza', 'body': 'Inhala por la nariz / Exhala por la boca. Imagina que el agua lava tus emociones. 5 respiraciones.'},
            {'title': 'Fuego — Transmutación', 'body': 'Inhala por la boca / Exhala por la nariz. Siente el calor purificando tu interior. 5 respiraciones.'},
            {'title': 'Aire — Apertura', 'body': 'Inhala por la boca / Exhala por la boca. Siente expansión en el área del corazón. 5 respiraciones.'},
            {'title': 'Éter — Conexión', 'body': 'Respiración sutil, suave y casi imperceptible por la nariz. Silencio interno. 5 respiraciones.'},
        ],
        'emotional_targets': ['desconexion', 'bloqueo', 'estres'],
        'body_zones': ['pecho', 'diafragma', 'extremidades'],
        'precaution': '',
        'order': 2,
    },

    # ── CAMPO ────────────────────────────────────────────────────────────────
    {
        'title': 'Armonización por Dedos',
        'subtitle': 'Jin Shin — Las 5 actitudes',
        'description': 'Cada dedo de la mano sostiene y libera una actitud emocional específica. Envolver el dedo suavemente basta para iniciar el proceso.',
        'instructions': 'Envuelve suavemente los dedos de una mano alrededor de un dedo de la otra. Sostén 2-5 minutos o hasta sentir que las pulsaciones de ambas manos se sincronizan.',
        'category': 'campo',
        'ui_mode': 'pasos',
        'duration_minutes': 5,
        'steps': [
            {'title': 'Elige', 'body': '¿Qué necesitas liberar? \n• Pulgar → Preocupación y rumia mental\n• Índice → Miedo e inseguridad\n• Medio → Ira y frustración\n• Anular → Tristeza y duelo\n• Meñique → Sobreesfuerzo y baja autoestima'},
            {'title': 'Sostén el dedo', 'body': 'Envuelve suavemente los dedos de una mano alrededor del dedo elegido de la otra. Sin presión, sin masaje. Solo el contacto.'},
            {'title': 'Espera la sincronía', 'body': 'Sostén de 2 a 5 minutos. Respira normalmente. Poco a poco, sentirás que las pulsaciones de ambas manos se sincronizan. Esa es la señal de completitud.'},
            {'title': 'Cierra', 'body': 'Suelta suavemente. Respira 3 veces. Puedes repetir con otro dedo si lo necesitas.'},
        ],
        'emotional_targets': ['miedo', 'ira', 'tristeza', 'ansiedad', 'estres'],
        'body_zones': ['extremidades'],
        'precaution': '',
        'order': 1,
    },
    {
        'title': 'Puntos Neurovasculares',
        'subtitle': 'Frontal-Occipital — Del pánico al lóbulo frontal',
        'description': 'Sostener frente y nuca simultáneamente devuelve el flujo sanguíneo de la amígdala (supervivencia) al lóbulo frontal (claridad). Excelente para el shock y el pánico.',
        'instructions': 'Coloca la palma de una mano en la frente y la palma de la otra en la base del cráneo. Sostén el toque 1-3 minutos sin presión.',
        'category': 'campo',
        'ui_mode': 'pasos',
        'duration_minutes': 3,
        'steps': [
            {'title': 'Posición', 'body': 'Siéntate o recuéstate cómodamente.'},
            {'title': 'Coloca las manos', 'body': 'Palma de una mano sobre la frente (eminencias frontales, encima de las cejas). Palma de la otra mano en la base del cráneo (occipucio).'},
            {'title': 'Sostén', 'body': 'Sin presión ni masaje. Solo el calor de las manos. Respira normalmente. Sostén entre 1 y 3 minutos.'},
            {'title': 'Observa', 'body': 'Notarás que la mente se calma y los pensamientos se vuelven más claros. El cuerpo puede relajarse solo.'},
        ],
        'emotional_targets': ['miedo', 'ansiedad', 'estres', 'confusion'],
        'body_zones': ['cabeza'],
        'precaution': '',
        'order': 2,
    },
    {
        'title': 'Equilibrio del Ombligo',
        'subtitle': 'Terapia de Polaridad — Centro y tercer ojo',
        'description': 'Conectar el ombligo con el tercer ojo balancea la energía entre el centro físico y el centro mental.',
        'instructions': 'Coloca suavemente el dedo medio de una mano en el ombligo, y el dedo medio de la otra en el entrecejo. Sostén el toque ligero hasta sentir un pulso sincronizado.',
        'category': 'campo',
        'ui_mode': 'pasos',
        'duration_minutes': 3,
        'steps': [
            {'title': 'Ubica los puntos', 'body': 'Dedo medio de una mano sobre el ombligo (puedes tocar sobre la ropa). Dedo medio de la otra mano sobre el entrecejo.'},
            {'title': 'Toque ligero', 'body': 'Sin presión. Es un toque de pluma. Respira naturalmente.'},
            {'title': 'Espera la sincronía', 'body': 'Mantén durante 2-3 minutos. Cuando sientas que las pulsaciones de ambos puntos laten al mismo ritmo, el ejercicio está completo.'},
        ],
        'emotional_targets': ['confusion', 'desconexion', 'ansiedad'],
        'body_zones': ['abdomen', 'cabeza'],
        'precaution': '',
        'order': 3,
    },
    {
        'title': 'Flujo Central',
        'subtitle': 'Jin Shin — Secuencia de la columna central',
        'description': 'Una secuencia de toques desde la coronilla hasta el cóccix armoniza el eje central del cuerpo y restaura el flujo de energía vital.',
        'instructions': 'Mano derecha siempre en la coronilla. La mano izquierda recorre los puntos del eje central, sosteniéndolos de a uno.',
        'category': 'campo',
        'ui_mode': 'pasos',
        'duration_minutes': 5,
        'steps': [
            {'title': 'Anclaje', 'body': 'Coloca los dedos de la mano DERECHA en la coronilla de la cabeza. Esta mano no se mueve durante todo el ejercicio.'},
            {'title': 'Entrecejo', 'body': 'Mano IZQUIERDA sobre el entrecejo. Sostén 1-2 min hasta sentir el pulso.'},
            {'title': 'Punta de la nariz', 'body': 'Mano IZQUIERDA sobre la punta de la nariz. Sostén.'},
            {'title': 'Esternón', 'body': 'Mano IZQUIERDA sobre el esternón (centro del pecho). Sostén.'},
            {'title': 'Plexo solar', 'body': 'Mano IZQUIERDA sobre el plexo solar (bajo el esternón). Sostén.'},
            {'title': 'Pubis', 'body': 'Mano IZQUIERDA sobre el pubis. Sostén.'},
            {'title': 'Cóccix', 'body': 'Mano IZQUIERDA sobre el cóccix (base de la columna). Sostén. Cierra el flujo.'},
        ],
        'emotional_targets': ['desconexion', 'agotamiento', 'bloqueo', 'estres'],
        'body_zones': ['cabeza', 'pecho', 'abdomen', 'sacro', 'espalda'],
        'precaution': '',
        'order': 4,
    },
    {
        'title': 'Cuna Occipital',
        'subtitle': 'Sostén del cráneo — Relajación de la columna',
        'description': 'Sostener el peso de la cabeza con las manos relaja toda la columna vertebral y libera la tensión crónica del cuello.',
        'instructions': 'Entrelaza las manos y colócalas bajo la base del cráneo, sosteniendo el peso de la cabeza suavemente. Deja que la columna se alargue sola.',
        'category': 'campo',
        'ui_mode': 'pasos',
        'duration_minutes': 5,
        'steps': [
            {'title': 'Posición', 'body': 'Acuéstate boca arriba en una superficie firme y cómoda.'},
            {'title': 'Entrelaza las manos', 'body': 'Entrelaza los dedos de ambas manos y colócalas bajo la base del cráneo (occipucio), sosteniendo el peso de la cabeza.'},
            {'title': 'Suelta el peso', 'body': 'No sostengas la cabeza con los músculos del cuello: deja que el peso de la cabeza descanse completamente en tus manos. Respira profundo.'},
            {'title': 'Recibe', 'body': 'Permanece así entre 3 y 5 minutos. Sentirás cómo la columna se alarga y relaja gradualmente.'},
        ],
        'emotional_targets': ['estres', 'agotamiento', 'ansiedad'],
        'body_zones': ['cabeza', 'espalda', 'garganta'],
        'precaution': '',
        'order': 5,
    },

    # ── PRESENCIA ────────────────────────────────────────────────────────────
    {
        'title': 'Declaración de Coherencia',
        'subtitle': 'Afirmación encarnada',
        'description': 'Una frase de empoderamiento, repetida mientras el cuerpo está en contacto energético, reprograma la respuesta del sistema nervioso ante ese patrón.',
        'instructions': 'Sostén los puntos frontales-occipitales (frente y nuca) o los Ganchos de Cook mientras repites en voz alta una frase de coherencia hasta que la voz suene firme y el cuerpo se relaje.',
        'category': 'presencia',
        'ui_mode': 'reflexion',
        'duration_minutes': 5,
        'steps': [
            {'title': '¿Qué necesitas afirmar?', 'body': 'Elige una frase que describa el estado o la creencia que quieres instalar. Ejemplos: "Estoy a salvo en el presente", "Merezco existir", "Elijo soltar esto", "Tengo derecho a ocupar espacio".'},
            {'title': 'Activa el contacto', 'body': 'Coloca una palma en la frente y otra en la nuca. O adopta la postura de los Ganchos de Cook. Activa el contacto energético primero.'},
            {'title': 'Repite en voz alta', 'body': 'Di la frase en voz alta, varias veces. Escucha tu propia voz. ¿Suena firme? ¿Temblorosa? ¿Congruente? Sigue repitiendo hasta que la voz suene clara y el cuerpo libere algo.'},
            {'title': 'Observa y cierra', 'body': 'Nota qué cambió en el cuerpo. ¿Hay alivio? ¿Alguna zona se relajó? Tres respiraciones profundas para cerrar.'},
        ],
        'emotional_targets': ['miedo', 'bloqueo', 'tristeza', 'desconexion'],
        'body_zones': ['pecho', 'cabeza'],
        'precaution': '',
        'order': 1,
    },
    {
        'title': 'Niño Interior',
        'subtitle': 'Imaginería — Rescate del pasado',
        'description': 'Tu yo adulto viaja a una escena del pasado para rescatar a tu versión más joven y decirle lo que necesitaba escuchar.',
        'instructions': 'En un estado de relajación profunda, visualiza la escena dolorosa. Entra como tu Yo Adulto, rescata al niño/a, y llévalo a un lugar seguro.',
        'category': 'presencia',
        'ui_mode': 'visualizacion',
        'duration_minutes': 10,
        'steps': [
            {'title': 'Entra en relajación', 'body': 'Cierra los ojos. 5 respiraciones profundas. Deja que el cuerpo se relaje completamente.'},
            {'title': 'La escena', 'body': 'Deja que aparezca una escena del pasado que todavía duele. No la busques: déjala venir. Obsérvala desde afuera, como en una película.'},
            {'title': 'Tu Yo Adulto entra', 'body': 'Imagina que tu versión actual, adulta, entra en esa escena. Mira al niño o niña que fuiste. Ve lo que necesitaba y no tuvo.'},
            {'title': 'Di lo que faltó', 'body': 'Acércate a tu versión joven. Dile lo que necesitaba escuchar: "Estás a salvo", "No es tu culpa", "Yo estoy aquí", "Eres suficiente".'},
            {'title': 'El lugar seguro', 'body': 'Toma a tu versión joven de la mano y llévalo/a a un lugar seguro, cálido y tuyo. Puede ser real o imaginado. Déjalo/a ahí, sabiendo que puedes volver cuando quieras.'},
            {'title': 'Regresa', 'body': 'Vuelve suavemente al presente. Respira 3 veces. Cuando estés listo/a, abre los ojos.'},
        ],
        'emotional_targets': ['tristeza', 'miedo', 'bloqueo', 'desconexion'],
        'body_zones': ['pecho', 'abdomen'],
        'precaution': 'Si surgen emociones muy intensas, puedes pausar y hacer 3 respiraciones normales antes de continuar.',
        'order': 2,
    },
    {
        'title': 'Corte de Lazos',
        'subtitle': 'Visualización — Liberación de vínculos energéticos',
        'description': 'Un proceso guiado para identificar y liberar los cordones energéticos que te mantienen atado a una persona o situación.',
        'instructions': 'Visualiza frente a ti a la persona o situación de la que quieres liberarte. Observa los cordones que os unen. Con una herramienta de luz, córtalos.',
        'category': 'presencia',
        'ui_mode': 'visualizacion',
        'duration_minutes': 8,
        'steps': [
            {'title': 'Entra en relajación', 'body': 'Cierra los ojos. 5 respiraciones. Cuerpo relajado, mente abierta.'},
            {'title': 'La persona o situación', 'body': 'Visualiza frente a ti a la persona, la situación o el patrón del que quieres liberarte. Obsérvalo/a sin juicio.'},
            {'title': 'Los cordones', 'body': 'Observa los cordones, cables o lazos que os conectan. ¿Dónde se unen a tu cuerpo? ¿De qué color son? ¿Cómo se sienten?'},
            {'title': 'La herramienta de luz', 'body': 'Imagina una herramienta de luz en tu mano: tijeras doradas, una espada de luz, un rayo de sol. Algo que sientas como tuyo.'},
            {'title': 'El corte', 'body': 'Con intención clara y sin ira, corta los lazos. Cada uno. Devuelve a la otra persona su energía, recupera la tuya. Ambos quedan libres.'},
            {'title': 'El sello', 'body': 'Visualiza una luz dorada sellando y sanando cada punto de tu cuerpo donde había un cordón. Respira.'},
            {'title': 'Cierre', 'body': 'Deja que la persona o situación se aleje. Agradece la experiencia. Regresa al presente. 3 respiraciones. Abre los ojos.'},
        ],
        'emotional_targets': ['bloqueo', 'tristeza', 'desconexion', 'miedo'],
        'body_zones': ['pecho', 'abdomen', 'sacro'],
        'precaution': 'Este proceso puede despertar emociones intensas. Es normal. No lo interrumpas: acompáñalo con respiración.',
        'order': 3,
    },
    {
        'title': 'Metáfora Sensorial',
        'subtitle': 'Transformación simbólica del bloqueo',
        'description': 'Darle forma, color y textura a una emoción o bloqueo permite al sistema nervioso procesarlo de una manera que las palabras no alcanzan.',
        'instructions': 'Localiza la emoción en tu cuerpo. Deja que tome una forma simbólica. Luego guía su transformación mediante la intención y la respiración.',
        'category': 'presencia',
        'ui_mode': 'reflexion',
        'duration_minutes': 8,
        'steps': [
            {'title': 'Localiza', 'body': '¿Dónde vives este peso, esta tensión, este bloqueo en el cuerpo? Ponle una ubicación precisa.'},
            {'title': 'Dale forma', 'body': 'Si esa sensación tuviera forma, ¿cuál sería? ¿Tiene peso? ¿Color? ¿Textura? ¿Es fría o caliente? No analices: déjala aparecer.'},
            {'title': 'Obsérvala sin luchar', 'body': 'Quédate con la imagen por un momento. Obsérvala sin tratar de cambiarla. Respira hacia ella, no lejos.'},
            {'title': 'La transformación', 'body': 'Con cada exhalación, imagina que esa forma comienza a cambiar sola. ¿Qué le pasa? ¿Se aligera? ¿Cambia de color? ¿Se disuelve? Sigue el proceso sin forzarlo.'},
            {'title': 'La nueva imagen', 'body': '¿En qué se convirtió? ¿Cómo se siente el cuerpo ahora en ese lugar? Quédate unos momentos con la nueva sensación.'},
        ],
        'emotional_targets': ['bloqueo', 'tristeza', 'ira', 'miedo', 'confusion'],
        'body_zones': ['pecho', 'abdomen', 'mandibula', 'espalda'],
        'precaution': '',
        'order': 4,
    },
]


class Command(BaseCommand):
    help = 'Seed de ejercicios de regulación somática'

    def handle(self, *args, **options):
        created = 0
        updated = 0
        for data in EJERCICIOS:
            obj, is_new = EjercicioRegulacion.objects.update_or_create(
                title=data['title'],
                defaults={**data},
            )
            if is_new:
                created += 1
            else:
                updated += 1
        self.stdout.write(self.style.SUCCESS(
            f'Regulación: {created} creados, {updated} actualizados — {created + updated} ejercicios totales'
        ))
