# Generated by Django 6.0.4 on 2026-06-17 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0002_dreamentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioRegulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField()),
                ('category', models.CharField(choices=[('respiracion', 'Respiración'), ('movimiento', 'Movimiento corporal'), ('sensorial', 'Anclaje sensorial'), ('cognitivo', 'Reencuadre cognitivo'), ('emocional', 'Regulación emocional')], max_length=20)),
                ('duration_minutes', models.IntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='regulacion/')),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='dreamentry',
            name='ai_insight',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dreamentry',
            name='archetype_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dreamentry',
            name='is_nauminto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dreamentry',
            name='nauminto_type',
            field=models.CharField(blank=True, choices=[('literal', 'Literal'), ('simbolico', 'Simbólico'), ('profetico', 'Profético'), ('lucido', 'Lúcido'), ('recurrente', 'Recurrente'), ('arquetipico', 'Arquetípico')], max_length=20),
        ),
        migrations.CreateModel(
            name='BitacoraEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('manual', 'Manual'), ('auto_test', 'Test completado'), ('auto_dream', 'Sueño registrado'), ('auto_espejo', 'Sesión Espejo'), ('auto_terapeuta', 'Consulta Terapéutica'), ('auto_oraculo', 'Oráculo consultado'), ('auto_regulacion', 'Ejercicio de regulación')], default='manual', max_length=30)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
