# Generated by Django 6.0.4 on 2026-06-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0003_ejercicioregulacion_dreamentry_ai_insight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraentry',
            name='entry_type',
            field=models.CharField(choices=[('sueno', 'Sueño'), ('sombra', 'Sombra'), ('patron', 'Patrón'), ('signo', 'Signo o síntoma'), ('manual', 'Nota libre'), ('auto_test', 'Test completado'), ('auto_espejo', 'Sesión Espejo'), ('auto_terapeuta', 'Consulta Terapéutica'), ('auto_oraculo', 'Oráculo consultado'), ('auto_regulacion', 'Ejercicio de regulación'), ('auto_dream', 'Sueño registrado')], default='manual', max_length=30),
        ),
    ]
