# Generated by Django 6.0.4 on 2026-06-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0004_bitacoraentry_add_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraentry',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
