# Generated by Django 6.0.4 on 2026-06-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0005_bitacoraentry_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejercicioregulacion',
            options={'ordering': ['category', 'order', 'title']},
        ),
        migrations.AddField(
            model_name='ejercicioregulacion',
            name='body_zones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ejercicioregulacion',
            name='emotional_targets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ejercicioregulacion',
            name='phases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ejercicioregulacion',
            name='precaution',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='ejercicioregulacion',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ejercicioregulacion',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ejercicioregulacion',
            name='ui_mode',
            field=models.CharField(choices=[('respiracion', 'Timer de respiración guiada'), ('pasos', 'Secuencia de pasos'), ('vocal', 'Guía vocal'), ('visualizacion', 'Visualización guiada'), ('reflexion', 'Reflexión libre')], default='pasos', max_length=20),
        ),
        migrations.AlterField(
            model_name='ejercicioregulacion',
            name='category',
            field=models.CharField(choices=[('aliento', 'Aliento'), ('integracion', 'Integración'), ('resonancia', 'Resonancia'), ('espectro', 'Espectro'), ('campo', 'Campo'), ('presencia', 'Presencia')], max_length=20),
        ),
    ]
