# Generated by Django 6.0.4 on 2026-06-19 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0006_regulacion_campos_ampliados'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNecesidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('tipo', models.CharField(choices=[('cotidiano', 'Cotidiano'), ('crisis', 'Crisis')], max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MomentoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirror.ejercicioregulacion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MomentoRegulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('image_key', models.CharField(blank=True, max_length=100)),
                ('duracion_min', models.PositiveSmallIntegerField(default=5)),
                ('tipo', models.CharField(choices=[('cotidiano', 'Cotidiano'), ('crisis', 'Crisis')], max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='momentos', to='mirror.categorianecesidad')),
                ('ejercicios', models.ManyToManyField(blank=True, through='mirror.MomentoEjercicio', to='mirror.ejercicioregulacion')),
            ],
            options={
                'ordering': ['tipo', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='momentoejercicio',
            name='momento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mirror.momentoregulacion'),
        ),
        migrations.AlterUniqueTogether(
            name='momentoejercicio',
            unique_together={('momento', 'ejercicio')},
        ),
    ]
