# Generated by Django 6.0.4 on 2026-06-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirror', '0007_add_momentos_regulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='espejo/attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Imagen'), ('pdf', 'PDF'), ('doc', 'Documento')], max_length=10),
        ),
    ]
