# Generated by Django 6.0.4 on 2026-06-17 06:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('framework_code', models.CharField(blank=True, max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('autoconsulta', 'Autoconsulta'), ('terapeuta', 'Terapeuta')], default='autoconsulta', max_length=20)),
                ('nombre_paciente', models.CharField(blank=True, max_length=200)),
                ('edad', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)])),
                ('ocupacion', models.CharField(blank=True, max_length=200)),
                ('motivo', models.TextField(default='')),
                ('intensidad', models.IntegerField(blank=True, null=True)),
                ('duracion', models.CharField(blank=True, choices=[('agudo', 'Agudo (<2 semanas)'), ('subagudo', 'Subagudo (2-6 semanas)'), ('cronico', 'Crónico (>6 semanas)')], max_length=20)),
                ('medicamentos_actuales', models.TextField(blank=True)),
                ('senales_alarma', models.BooleanField(default=False)),
                ('prioridad_sintoma', models.TextField(blank=True)),
                ('marcos_recomendados', models.JSONField(blank=True, default=list)),
                ('diagnostico_final', models.TextField(blank=True)),
                ('propuesta_terapeutica', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paso_actual', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_terapeuta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoPropuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('etiologia', models.TextField(blank=True)),
                ('mecanismo', models.TextField(blank=True)),
                ('patron_diagnostico', models.TextField(blank=True)),
                ('protocolo_indicado', models.TextField(blank=True)),
                ('contraindicaciones', models.TextField(blank=True)),
                ('integracion', models.TextField(blank=True)),
                ('fue_confirmado_por_usuario', models.BooleanField(default=False)),
                ('diagnostico_id', models.CharField(blank=True, max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='terapeuta.consulta')),
                ('marco_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos', to='terapeuta.marcoevaluacion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SintomaConfirmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintoma_texto', models.CharField(max_length=200)),
                ('presente', models.BooleanField(default=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sintomas', to='terapeuta.diagnosticopropuesto')),
            ],
        ),
        migrations.CreateModel(
            name='TecnicaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo_interno', models.CharField(max_length=20, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('marco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicas', to='terapeuta.marcoevaluacion')),
            ],
            options={
                'ordering': ['marco__orden', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField(blank=True)),
                ('pregunta_id', models.CharField(blank=True, max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_respuestas', to='terapeuta.consulta')),
                ('tecnica_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='terapeuta.tecnicaevaluacion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='diagnosticopropuesto',
            name='tecnica_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos', to='terapeuta.tecnicaevaluacion'),
        ),
        migrations.CreateModel(
            name='SeleccionTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fue_recomendada_por_sistema', models.BooleanField(default=False)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='terapeuta.consulta')),
                ('tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecciones', to='terapeuta.tecnicaevaluacion')),
            ],
            options={
                'unique_together': {('consulta', 'tecnica')},
            },
        ),
    ]
