# Generated by Django 6.0.4 on 2026-06-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0002_initial'),
        ('terapeuta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='perfil_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='practitioners.temporaryprofile'),
        ),
    ]
