# Generated by Django 6.0.4 on 2026-07-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0002_consulta_add_perfil_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='ejes_resultado',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='consulta',
            name='formula_mtc',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='consulta',
            name='signos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='consulta',
            name='sistemas_afectados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnosticopropuesto',
            name='confianza',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticopropuesto',
            name='evidencia',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diagnosticopropuesto',
            name='puntaje',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
