# Generated by Django 6.0.4 on 2026-06-15 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('birth', '0001_initial'),
        ('practitioners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdata',
            name='temp_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_data', to='practitioners.temporaryprofile'),
        ),
        migrations.AddField(
            model_name='birthdata',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='birthreport',
            name='birth_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='birth.birthdata'),
        ),
        migrations.AlterUniqueTogether(
            name='birthreport',
            unique_together={('birth_data', 'report_type')},
        ),
    ]
