# Generated by Django 6.0.4 on 2026-06-17 04:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaFractal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('nombre_arcano', models.CharField(max_length=100)),
                ('verbo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('arcano', 'Arcano Mayor'), ('sefirot', 'Sefirot')], default='arcano', max_length=10)),
                ('descripcion_breve', models.TextField()),
                ('descripcion_larga', models.TextField(blank=True)),
                ('sefirot_nombre', models.CharField(blank=True, max_length=50)),
                ('es_especial', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Carta Fractal',
                'verbose_name_plural': 'Cartas Fractales',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SesionOraculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_oraculo', models.CharField(choices=[('tarot', 'Tarot Terapéutico'), ('iching', 'I Ching'), ('fractal', 'Oráculo Fractal')], max_length=20)),
                ('pregunta', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('guardada', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_oraculo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Oráculo',
                'verbose_name_plural': 'Sesiones de Oráculo',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LecturaTarot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tirada', models.CharField(max_length=20)),
                ('cartas', models.JSONField(default=list)),
                ('interpretacion', models.TextField(blank=True)),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lectura_tarot', to='oraculo.sesionoraculo')),
            ],
            options={
                'verbose_name': 'Lectura de Tarot',
            },
        ),
        migrations.CreateModel(
            name='LecturaIChing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineas', models.JSONField(default=list)),
                ('hexagrama_primario_numero', models.PositiveIntegerField(blank=True, null=True)),
                ('hexagrama_primario_nombre', models.CharField(blank=True, max_length=100)),
                ('hexagrama_secundario_numero', models.PositiveIntegerField(blank=True, null=True)),
                ('hexagrama_secundario_nombre', models.CharField(blank=True, max_length=100)),
                ('interpretacion', models.TextField(blank=True)),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lectura_iching', to='oraculo.sesionoraculo')),
            ],
            options={
                'verbose_name': 'Lectura I Ching',
            },
        ),
        migrations.CreateModel(
            name='LecturaFractal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invertida', models.BooleanField(default=False)),
                ('interpretacion', models.TextField(blank=True)),
                ('carta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oraculo.cartafractal')),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lectura_fractal', to='oraculo.sesionoraculo')),
            ],
            options={
                'verbose_name': 'Lectura Fractal',
            },
        ),
    ]
