# Generated by Django 6.0.4 on 2026-06-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='color_palette',
            field=models.CharField(choices=[('cosmos', 'Cosmos (por defecto)'), ('aurora', 'Aurora Boreal'), ('terra', 'Tierra Viva'), ('obsidian', 'Obsidiana'), ('sakura', 'Sakura')], default='cosmos', max_length=20),
        ),
    ]
