# Generated by Django 6.0.4 on 2026-06-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_color_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_priorities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='map_aesthetic',
            field=models.CharField(choices=[('cosmos', 'Cósmico'), ('mandala', 'Mandala')], default='cosmos', max_length=20),
        ),
    ]
