# Generated by Django 6.0.4 on 2026-06-15 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practitioners', '0001_initial'),
        ('psychometrics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryprofile',
            name='assigned_tests',
            field=models.ManyToManyField(blank=True, to='psychometrics.test'),
        ),
        migrations.AddField(
            model_name='temporaryprofile',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temporaryprofile',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionnote',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='practitioners.temporaryprofile'),
        ),
        migrations.AddField(
            model_name='therapysession',
            name='practitioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='therapysession',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='practitioners.temporaryprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('practitioner', 'day_of_week', 'start_time')},
        ),
    ]
