# Generated by Django 6.0.4 on 2026-06-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, unique=True)),
                ('week_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('registros_nuevos', models.IntegerField(default=0)),
                ('activacion_pct', models.FloatField(default=0)),
                ('retencion_d7_pct', models.FloatField(default=0)),
                ('retencion_d30_pct', models.FloatField(default=0)),
                ('sesiones_espejo_avg', models.FloatField(default=0)),
                ('navegantes_total', models.IntegerField(default=0)),
                ('navegantes_nuevos_semana', models.IntegerField(default=0)),
                ('mrr_estimado_usd', models.FloatField(default=0)),
                ('email_open_rate_pct', models.FloatField(default=0)),
                ('email_ctr_pct', models.FloatField(default=0)),
                ('suscriptores_total', models.IntegerField(default=0)),
                ('visitas_landing', models.IntegerField(default=0)),
                ('visitas_unicas', models.IntegerField(default=0)),
                ('fuentes_top', models.JSONField(default=dict)),
                ('escenario', models.CharField(choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo')], default='rojo', max_length=10)),
                ('alertas', models.JSONField(default=list)),
                ('decision_sugerida', models.TextField(blank=True)),
                ('md_snapshot', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
    ]
