# Generated by Django 6.0.4 on 2026-06-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpisnapshot',
            name='instagram_alcance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpisnapshot',
            name='instagram_seguidores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpisnapshot',
            name='posts_publicados_semana',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpisnapshot',
            name='serpbear_keywords_top3',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='kpisnapshot',
            name='serpbear_posicion_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='kpisnapshot',
            name='serpbear_subiendo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpisnapshot',
            name='trafico_instagram',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpisnapshot',
            name='trafico_linkedin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kpisnapshot',
            name='trafico_tiktok',
            field=models.IntegerField(default=0),
        ),
    ]
