# Generated by Django 6.0.4 on 2026-06-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_kpisnapshot_instagram_alcance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpisnapshot',
            name='tiktok_seguidores',
            field=models.IntegerField(default=0),
        ),
    ]
