# Generated by Django 6.0.4 on 2026-07-14 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_kpisnapshot_top_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('pagina', models.CharField(blank=True, max_length=300)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('revisado', 'Revisado'), ('resuelto', 'Resuelto')], default='nuevo', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='BugScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.BinaryField()),
                ('content_type', models.CharField(default='image/png', max_length=60)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capturas', to='reports.bugreport')),
            ],
        ),
    ]
