# Generated by Django 6.0.4 on 2026-06-15 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practitioners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('dimension', models.CharField(choices=[('mente', 'Mente'), ('emociones', 'Emociones'), ('cuerpo', 'Cuerpo'), ('vinculos', 'Vínculos'), ('proposito', 'Propósito'), ('sombra', 'Sombra'), ('tipologia', 'Tipología')], max_length=20)),
                ('instrument_type', models.CharField(choices=[('clinical', 'Clínico validado'), ('adapted', 'Adaptado'), ('custom', 'Endonauta')], default='adapted', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('estimated_minutes', models.IntegerField(default=5)),
                ('token_cost', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dimension_key', models.CharField(blank=True, max_length=50)),
                ('scale', models.CharField(choices=[('likert5', 'Likert 1-5 frecuencia'), ('likert5a', 'Likert 1-5 acuerdo'), ('likert4', 'Likert 0-4'), ('likert3', 'Likert 0-3'), ('likert7', 'Likert 1-7'), ('binary', 'Sí/No')], default='likert5', max_length=20)),
                ('reverse_scored', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='psychometrics.test')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_scores', models.JSONField(default=dict)),
                ('evaluation', models.JSONField(default=dict)),
                ('ai_insight', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('temp_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_results', to='practitioners.temporaryprofile')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychometrics.test')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
