# Generated by Django 6.0.4 on 2026-06-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychometrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='dimension',
            field=models.CharField(choices=[('identidad', 'Identidad'), ('emociones', 'Emociones'), ('cuerpo', 'Cuerpo'), ('vinculos', 'Vínculos'), ('sombra', 'Sombra'), ('espiritualidad', 'Espiritualidad'), ('suenos', 'Sueños'), ('proposito', 'Propósito'), ('comunidad', 'Comunidad'), ('abundancia', 'Abundancia'), ('creatividad', 'Creatividad'), ('mente', 'Mente')], max_length=20),
        ),
    ]
