# Generated by Django 6.0.4 on 2026-06-15 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0002_initial'),
        ('psychometrics', '0002_alter_test_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='temp_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_test_results', to='practitioners.temporaryprofile'),
        ),
    ]
