# birth/meanings.py — Textos interpretativos profundos, en segunda persona, lenguaje simple y directo.

# ── Carta Astral ──────────────────────────────────────────────────────────────

PLANET_MEANINGS = {
    'sun':     'Tu identidad central — la esencia que más trabajo cuesta integrar y que más alegría produce cuando se vive con plenitud. No es cómo te ven ni cómo te sientes: es lo que viniste a ser. El signo del Sol muestra el estilo con que expresas esa identidad. Cuando tu vida no refleja la energía de tu Sol, hay un vacío que no desaparece con logros externos.',
    'moon':    'Tu mundo emocional más íntimo y las necesidades que rara vez declaras pero que gobiernan gran parte de tus decisiones. La Luna muestra qué necesitas para sentirte seguro, cómo reaccionas instintivamente antes de que la razón intervenga, y la huella emocional de tu infancia. Comprender tu Luna es entender por qué reaccionas como reaccionas en los momentos de tensión o vulnerabilidad.',
    'mercury': 'Tu mente y tu forma de comunicarte con el mundo. Muestra cómo procesas la información, en qué ritmo funciona tu pensamiento y qué estilo de expresión te resulta natural. Explica por qué algunas conversaciones te estimulan enormemente y otras te agotan, y los malentendidos recurrentes en tu vida — no porque seas difícil, sino porque tu forma de codificar el mundo es específica.',
    'venus':   'Lo que genuinamente valoras, deseas y encuentras bello. Venus no es solo amor romántico: es tu mapa interno del placer, la abundancia y el tipo de conexión que te alimenta. Muestra también tu relación más profunda con el merecer — contigo mismo y con el dinero. Cuando Venus no está integrado, buscas afuera lo que sientes que no puedes darte a ti mismo.',
    'mars':    'Tu energía de acción, deseo y afirmación personal. Marte muestra cómo vas tras lo que quieres, cómo manejas la rabia y la frustración, y qué te activa desde adentro. Cuando Marte está reprimido o mal dirigido, aparece la inercia, la irritabilidad crónica o la agresividad fuera de contexto. Entender tu Marte es entender cómo movilizas tu vida sin quemarte ni paralizarte.',
    'jupiter': 'Tu principio de expansión y abundancia — dónde encuentras facilidad natural, suerte y recursos disponibles. También muestra cómo te relacionas con la fe y el sentido de vida. Su sombra es la tendencia a exagerar o a dar por hecho lo que viene fácil. Lo que nos da sin esfuerzo, rara vez lo valoramos tan profundo como lo que nos costó.',
    'saturn':  'Tus lecciones más importantes de esta vida — las áreas donde sientes presión o miedo recurrente, pero que son exactamente las que más recompensa traen cuando se trabajan. Saturno no es el planeta malo: es el que exige madurez. Muestra dónde la disciplina sostenida construye algo que dura. La resistencia que sientes ante tu Saturno es proporcional al crecimiento que te espera si lo atraviesas.',
    'uranus':  'Tu impulso de liberación y originalidad — donde la convención nunca te bastará y tienes que encontrar tu propio camino aunque incomode. Como planeta generacional, todos de tu época lo tienen en el mismo signo, pero la casa y los aspectos dicen dónde te afecta personalmente. Donde está Urano, espera disrupciones que al final siempre abren algo que estaba cerrado.',
    'neptune': 'Tu conexión con lo invisible — espiritualidad, imaginación, empatía profunda y el deseo de disolverse en algo mayor. También donde puedes caer en la ilusión o el autoengaño. Como planeta generacional, la casa y aspectos muestran dónde tu intuición es más viva y también dónde más cuidado necesitas para no perder el norte.',
    'pluto':   'Tu potencial de transformación radical. Plutón actúa donde la vida te llevará a destruir algo para reconstruirlo desde cero — no una vez sino varias. Como planeta generacional, la casa y aspectos muestran dónde ocurre en tu vida personal: dónde tienes más intensidad y más capacidad de renacer. Donde está Plutón, la superficie nunca es suficiente.',
}

SIGN_MEANINGS = {
    'Aries':       'Con iniciativa directa y valentía impulsiva. Ves la oportunidad y vas sin esperar permiso. Tu sombra es la impaciencia y la dificultad para sostener lo que iniciaste; tu don es encender fuego donde todo estaba frío. Esta energía funciona mejor cuando hay un desafío real — sin reto, la motivación se evapora.',
    'Tauro':       'Con pausa, sensorialidad y necesidad profunda de estabilidad. No se apresura — construye con calma y permanece. Tu sombra es la rigidez ante el cambio y el apego a lo conocido; tu don es crear solidez y placer en lo que tocas. La confianza aquí se construye a través de la experiencia concreta, no de las ideas abstractas.',
    'Géminis':     'Con curiosidad intensa y una mente que necesita varios estímulos al mismo tiempo. Tu sombra es la dispersión y la dificultad para profundizar cuando la novedad se acaba; tu don es hacer circular ideas y conectar mundos distintos con ligereza. Esta energía vive en el lenguaje, las conexiones y la capacidad de ver múltiples perspectivas simultáneas.',
    'Cáncer':      'Con sensibilidad e intuición profunda — se mueve siempre desde el corazón. Necesita seguridad emocional para abrirse; sin ella, se cierra y protege. Tu sombra es absorber el estado de otros como propio y aferrarte al pasado; tu don es crear pertenencia y cuidar desde un lugar genuinamente nutrido.',
    'Leo':         'Con generosidad, creatividad y necesidad real de expresarse y ser visto en lo que tiene de único. Busca brillar no por vanidad sino porque la expresión auténtica es su forma de vivir. Tu sombra es la dependencia del reconocimiento externo; tu don es irradiar calidez de un modo que activa lo mismo en los demás.',
    'Virgo':       'Con análisis, precisión y orientación profunda al servicio y la mejora continua. Percibe los detalles que otros pasan por alto. Tu sombra es la autocrítica excesiva y el perfeccionismo que inmoviliza; tu don es la capacidad de discernir lo esencial y mejorar lo que toca con método y cuidado real.',
    'Libra':       'Con búsqueda de equilibrio y necesidad profunda de justicia y armonía relacional. Se activa en el espejo del otro — en el diálogo y el encuentro genuino. Tu sombra es la indecisión y ceder para evitar el conflicto; tu don es crear espacios donde los distintos pueden coexistir sin que nadie tenga que perderse.',
    'Escorpio':    'Con intensidad y resistencia natural a quedarse en la superficie de nada. Va al fondo — quiere saber lo que hay debajo, lo que no se dice. Tu sombra es el control y la dificultad para confiar; tu don es la capacidad de sostener lo oscuro sin huir de él y transformar lo que para otros sería insoportable.',
    'Sagitario':   'Con expansión y necesidad de horizonte siempre más amplio. No tolera los techos bajos — necesita explorar y encontrar la verdad más allá de lo inmediato. Tu sombra es la impaciencia con los límites y predicar más de lo que integra; tu don es ver el panorama completo cuando otros se pierden en los detalles.',
    'Capricornio': 'Con ambición sostenida y visión de largo plazo que pocos tienen. Construye para durar — paso a paso, sin atajos. Tu sombra es la rigidez y dificultad para disfrutar el camino sin la meta en mente; tu don es la capacidad de estructurar y construir algo con legado real.',
    'Acuario':     'Con originalidad y resistencia genuina a lo que limita la libertad o la evolución colectiva. Piensa diferente por naturaleza, no como pose. Tu sombra es la desconexión emocional y priorizar ideas sobre personas concretas; tu don es ver lo que nadie más ve todavía y aportar perspectivas que abren caminos nuevos.',
    'Piscis':      'Con empatía y permeabilidad que disuelve los límites entre tú y el mundo. Siente antes de pensar y comprende sin necesitar explicaciones. Tu sombra es la dificultad para mantener límites propios y la tendencia a la evasión; tu don es la capacidad de conectar con lo que es invisible para otros — intuición, arte, compasión sin condiciones.',
}

ASC_MEANINGS = {
    'Aries':       'El Ascendente Aries es tu escudo y tu lanza: la primera impresión que das es de alguien directo, seguro y listo para moverse. La gente te percibe como alguien que actúa antes de deliberar, lo cual atrae tanto como intimida. Tu reto con este ascendente es aprender a iniciar con conciencia, no solo con impulso — porque la velocidad puede quemar pasos que importan.',
    'Tauro':       'El Ascendente Tauro proyecta solidez y calma. La gente siente que puede confiar en ti antes de que abras la boca. Te acercas a lo nuevo con pausa — observas antes de comprometerte. El reto es que tu presencia tan confiable puede generar en otros la expectativa de que siempre estés disponible y estable, aunque por dentro no lo estés.',
    'Géminis':     'El Ascendente Géminis te hace aparecer como alguien vivo, curioso y adaptable. Causas impresión de agilidad mental y capacidad de conectar con cualquier persona. El reto es que esta versatilidad puede hacerte parecer superficial a quienes no te conocen de fondo — tu profundidad real se muestra solo en relaciones de confianza sostenida.',
    'Cáncer':      'El Ascendente Cáncer proyecta calidez y receptividad desde el primer encuentro. La gente siente que eres alguien que escucha y que no juzga. El reto es que absorbes el estado emocional del entorno antes de procesar el tuyo propio — en contextos cargados, esto puede dejarte sin suelo. Distinguir qué sientes tú versus qué captás de otros es una práctica de vida con este ascendente.',
    'Leo':         'El Ascendente Leo entra a los espacios con presencia magnética — no siempre buscada, pero difícil de ignorar. Tu primer impacto es de generosidad y vitalidad. El reto es que la expectativa de brillar puede sentirse como presión: la máscara social Leona a veces es difícil de quitarse. La autenticidad — mostrar cuando no estás bien — es el trabajo con este ascendente.',
    'Virgo':       'El Ascendente Virgo proyecta competencia tranquila y atención. La gente te percibe como alguien organizado y confiable en los detalles. Tu primera impresión raramente es llamativa — pero deja una sensación de solidez. El reto es que la autocrítica que diriges a ti mismo a menudo se proyecta como criterio hacia otros, lo que puede hacer tu presencia parecer exigente aunque no sea tu intención.',
    'Libra':       'El Ascendente Libra proyecta gracia y una capacidad natural de hacer que el entorno se sienta más armonioso. La gente te percibe como diplomático y agradable. El reto es que la necesidad de mantener esa armonía puede llevarte a evitar conflictos necesarios — a decir lo que el otro quiere escuchar antes que lo que verdaderamente piensas.',
    'Escorpio':    'El Ascendente Escorpio proyecta intensidad y profundidad desde el primer momento — a veces incluso antes de hablar. La gente siente que hay más de lo que muestras, lo cual genera fascinación o incomodidad. Tu mirada tiene peso. El reto es que la guardia alta puede aislar: protege pero también impide conexiones genuinas que solo ocurren cuando te arriesgas a ser visto.',
    'Sagitario':   'El Ascendente Sagitario proyecta optimismo y una energía que invita a expandirse. La gente te percibe como alguien libre y generoso en perspectivas. El reto es que la promesa implícita de expansión puede generar expectativas que no siempre puedes cumplir, y tu tendencia a ser directo puede resultar brusca cuando no se acompaña de tacto.',
    'Capricornio': 'El Ascendente Capricornio proyecta autoridad tranquila y madurez — incluso desde joven. Tu primer impacto es de competencia y responsabilidad. El reto es que esa imagen de solidez puede hacer que otros no te ofrezcan apoyo cuando lo necesitas, asumiendo que siempre puedes solo. Y que tú mismo puede que tardes en pedir ayuda porque "no encaja" con quien proyectas ser.',
    'Acuario':     'El Ascendente Acuario proyecta originalidad y una distancia que hace que la gente sienta que eres difícil de encasillar. Tu primera impresión es de alguien que piensa diferente e imprevisible en el buen sentido. El reto es que esa distancia puede ser leída como frialdad, cuando hay una calidez real debajo que simplemente necesita más tiempo para aparecer.',
    'Piscis':      'El Ascendente Piscis proyecta sensibilidad y una receptividad que hace que la gente sienta que puede contarte cosas que no le cuenta a otros. Tu primer impacto es suave, empático y algo misterioso. El reto es que esa permeabilidad puede hacer que los límites sean difusos — tanto en cómo te presentas (cambiando según el contexto) como en cuánto absorbes del estado del entorno sin darte cuenta.',
}

MC_MEANINGS = {
    'Aries':       'Tu vocación tiene energía pionera — eres reconocido por poner en movimiento lo que otros todavía están pensando. Construyes tu lugar en el mundo siendo el que abre el camino sin garantías. El reto es que la impaciencia puede hacerte saltar a lo siguiente antes de consolidar lo que iniciaste. Tu legado real se construye cuando aprendes a ser valiente Y consistente.',
    'Tauro':       'Eres recordado por lo que construyes con constancia — cosas que duran. El mundo te reconoce por tu confiabilidad y tu capacidad de producir valor real, no promesas vacías. El reto es que la búsqueda de seguridad puede mantenerte en caminos conocidos más tiempo del necesario, cuando el salto hacia algo nuevo es exactamente lo que tu vocación necesita para crecer.',
    'Géminis':     'Eres reconocido por tu capacidad de comunicar y hacer circular información entre mundos distintos. Tu vocación tiene lenguaje en el centro — escribir, hablar, enseñar, mediar, traducir. El mundo te recuerda por cómo hiciste que algo complejo se entendiera con facilidad. El reto es la multiplicidad de intereses que puede dispersar la dirección vocacional.',
    'Cáncer':      'Eres recordado por tu capacidad de crear pertenencia y cuidar en lo que haces. Tu vocación tiene un núcleo de nutrición — sea en educación, salud, familia o comunidad. El mundo te recuerda por cómo hiciste sentir a las personas en casa. El reto es que dar sin límite agota la fuente: tu vocación prospera cuando tú también eres sostenido.',
    'Leo':         'Eres reconocido por tu creatividad y la capacidad de liderar desde el corazón, no desde la autoridad formal. Tu vocación involucra expresión — arte, liderazgo, enseñanza. El mundo te recuerda porque cuando estabas en tu elemento, hacías que otros también quisieran brillar. El reto es el miedo a no ser suficientemente "especial" — tu mayor obra surge cuando dejas de compararte y simplemente te expresas.',
    'Virgo':       'Eres recordado por la excelencia silenciosa de tu trabajo. Tu vocación involucra mejora continua — análisis, salud, proceso, técnica. El mundo recuerda lo bien que hacías las cosas, no lo mucho que hablabas de hacerlas. El reto es el perfeccionismo que hace que tu trabajo nunca se comparta porque "todavía le falta".',
    'Libra':       'Eres reconocido por tu capacidad de crear puentes y armonía donde hay división. Tu vocación involucra relaciones, mediación, estética o justicia. El reto es que evitar el conflicto a cualquier costo puede llevarte a compromisos que traicionan tu propia visión — tu vocación madura cuando aprendes que la verdad también es una forma de armonía.',
    'Escorpio':    'Eres recordado por tu profundidad y poder de transformar lo que tocas. Tu vocación involucra lo que está oculto o profundo — psicología, investigación, sanación, poder. El mundo te recuerda porque te enfrentaste a lo que otros evitaban. El reto es el control — la necesidad de tener las riendas puede limitar las colaboraciones que catalizarían tu mayor impacto.',
    'Sagitario':   'Eres reconocido por tu visión y tu capacidad de expandir horizontes en quienes te rodean. Tu vocación involucra enseñanza, filosofía, exploración. El mundo te recuerda porque abriste mundos que otros no imaginaban. El reto es que la pasión por el conocimiento puede llevarte a abarcar tanto que tu impacto real se diluye — profundizar en un área puede ser más transformador que tocar todo desde afuera.',
    'Capricornio': 'Eres recordado por lo que construiste con visión de largo plazo — instituciones, estructuras, carreras que duran más que tú. El mundo te recuerda por la solidez de tu obra y la integridad con que la edificaste. El reto es que la ambición puede hacer que sacrifiques la vida personal en el altar de los logros.',
    'Acuario':     'Eres reconocido por tu originalidad y visión de futuro — por ver lo que nadie más tenía todavía. Tu vocación involucra innovación, tecnología, activismo. El reto es la distancia emocional — las ideas revolucionarias necesitan también la calidez humana para aterrizar y transformar vidas concretas.',
    'Piscis':      'Eres recordado por tu sensibilidad y una dimensión espiritual o artística que atravesaba todo lo que hacías. Tu vocación involucra sanación, arte, espiritualidad o trabajo donde la empatía es el instrumento central. El mundo te recuerda porque había algo en lo que hacías que iba más allá de la técnica — algo que tocaba el alma. El reto es el límite: sin estructura, la sensibilidad se dispersa y el impacto real nunca cristaliza.',
}

# ── Human Design ──────────────────────────────────────────────────────────────

HD_TYPE_MEANINGS = {
    'Generador': 'El Generador es el motor del mundo — cerca del 37% de la humanidad. Tu energía sacral es la más sostenida y poderosa del planeta, diseñada para crear y responder. La palabra clave es responder: tu energía funciona de verdad cuando reacciona a algo externo antes de que la mente decida si "tiene sentido". Cuando inicias desde la cabeza sin un "sí" visceral, el camino se vuelve árido y termina en frustración. La Satisfacción — hacer lo que genuinamente te enciente — es tu indicador de que estás en el camino correcto. Aprende a distinguir la respuesta sacral genuina (ese "uh-huh" que surge del centro del cuerpo) de la decisión mental que luego intentas convencer.',

    'Generador Manifestante': 'El Generador Manifestante (aprox. 33%) es el tipo más rápido y versátil. Tienes energía sacral Y capacidad de iniciar directamente — lo que te da una combinación de potencia y velocidad que puede ser extraordinaria o caótica. Tu ciclo natural: sentir → responder → informar → hacer. El paso que más se saltea es informar: comunicar tus intenciones antes de lanzarte reduce la resistencia del entorno enormemente. Sin ese paso, tu velocidad genera confusión a tu alrededor. Tu sombra es la impulsividad y la frustración cuando tienes que explicar tus movimientos. La velocidad real no es sin comunicación — es con comunicación efectiva.',

    'Manifestador': 'El Manifestador (aprox. 9%) es el único tipo diseñado para iniciar sin señales del entorno. Tienes energía que puede activar cosas de la nada — una idea, un proyecto, un movimiento. Tu don de iniciación puede generar resistencia si no va acompañado de un gesto clave: informar. No pedir permiso — informar. "Voy a hacer X" dicho antes de actuar, no después, cambia radicalmente cómo el entorno responde a ti. Tu sombra más profunda es el aislamiento: la sensación de que tienes que hacerlo todo solo porque nadie entiende tu ritmo. La Paz — moverse sin fricción innecesaria — aparece cuando aprendes a incluir a otros sin perder tu autonomía.',

    'Proyector': 'El Proyector (aprox. 20%) no tiene energía sacral propia — está diseñado para guiar, no para producir. Tu función es ver al otro y al sistema con claridad que nadie desde adentro puede tener. Tienes un don natural para la orientación y el reconocimiento del talento ajeno. Pero ese don solo es recibido cuando se te invita a compartirlo. Ofrecer tu visión sin invitación — por brillante que sea — genera rechazo. Esperar la invitación no es pasividad: es saber que cuando llega, tu impacto es exponencialmente mayor. Tu sombra más profunda es la amargura — sentir que tienes mucho para dar y que nadie lo ve. Esa amargura aparece cuando te comparas con los generadores y usas su energía como estándar.',

    'Reflector': 'El Reflector (menos del 1%) es el tipo más raro y más abierto. No tienes centros definidos — eres puro espacio de recepción y amplificación. Tu función es reflejar la salud de tu comunidad: cuando estás bien, la comunidad está bien; cuando estás mal, generalmente es porque el entorno no te nutre. Tu mayor desafío es la identidad: sin centros definidos, es fácil absorber las energías de todos y perder el hilo de quién eres tú. Las decisiones importantes requieren tiempo — un ciclo lunar completo (29 días) te permite ver cómo se siente esa decisión en distintos momentos antes de comprometerte. La Sorpresa — la capacidad de ser genuinamente asombrado — es tu firma cuando estás en el camino correcto.',
}

HD_PROFILE_MEANINGS = {
    '1/1': 'El Investigador Doble necesita saber — realmente saber — antes de sentirse seguro de moverse. Esta búsqueda de base no es inseguridad: es tu mecanismo de funcionamiento genuino. Cuando tienes conocimiento sólido, te mueves con confianza contagiosa. Sin esa base, hay ansiedad de fondo que no desaparece hasta llenar el vacío de información. La trampa es el estudio infinito como forma de evitar la acción — hay un punto donde ya sabes suficiente para dar el paso. Tu propósito se expresa a través de compartir el conocimiento que acumulas, aunque sientas que "todavía te falta saber más".',
    '1/2': 'Estudias profundo en soledad y de repente eres llamado a compartir lo que encontraste, aunque no te lo hayas propuesto. Tienes dones naturales que no siempre reconoces en ti mismo — otros los ven antes que tú. Alternas entre períodos de estudio intenso y períodos donde necesitas retirarte para integrar. Tu sombra es la incomodidad cuando llegas a compartir: no siempre quieres ser visto. El llamado llega de todas formas. Tu camino es aprender a discernir qué invitaciones genuinamente te resuenan versus cuáles solo te sacan de tu centro.',
    '1/3': 'El Investigador/Mártir aprende desde la base pero prueba todo en la vida real hasta que deja de funcionar. Eres el gran empirista del Diseño Humano: tu conocimiento viene de haber intentado, fallado y vuelto a intentar. Tus "fracasos" no son tropiezos — son los datos más valiosos de tu investigación. Esta forma de aprender implica ciclos de inicio y fin en relaciones, proyectos y caminos de vida. El secreto es reconocer que cada cosa que "no funcionó" te dio algo que todavía llevas contigo. Tu autoridad real se construye sobre la experiencia vivida, no sobre lo que te enseñaron que debería funcionar.',
    '1/4': 'Construyes conocimiento y lo compartes a través de relaciones de confianza. Tu red no es estrategia de networking — es el canal real de tu propósito. Las personas cercanas reconocen tu valor y te abren las puertas al siguiente paso. Necesitas una base sólida de conocimiento para sentirte seguro en esas relaciones, pero también necesitas que las relaciones sean estables para que tu información fluya. Tu sombra es que cuando la base se siente incierta, aparece ansiedad en los vínculos. Y cuando las relaciones cambian abruptamente, puede sentirse como pérdida del propósito.',
    '2/1': 'Tienes dones naturales que emergen en soledad y una necesidad profunda de una base firme. No siempre sabes que eres bueno en lo que eres bueno — necesitas que otro te lo señale. Tiendes a ser llamado a salir cuando las personas que te observan reconocen algo que tú mismo no ves. Tu ciclo natural: retirarte para profundizar → ser llamado → salir → compartir → volver a retirarte. El reto es que el mundo moderno no favorece el retiro — pero sin él, tu energía y tu claridad se erosionan.',
    '2/2': 'Tienes dones que emergen naturalmente cuando nadie está mirando, activados por el ambiente correcto, no por el esfuerzo. Necesitas mucha soledad para estar bien — esto no es timidez, es una necesidad de diseño. Cuando estás en el ambiente correcto y con las personas adecuadas, algo en ti florece casi sin querer. Tu sombra es que puedes ser llamado a salir constantemente sin reconocer que estás dando más de lo que repones. Proteger tu tiempo de soledad no es egoísmo — es mantenimiento de lo que te hace funcionar.',
    '2/3': 'Alternas entre necesitar retiro profundo y vivir un proceso de aprendizaje por ensayo y error muy activo. Por dentro necesitas espacio y silencio; por fuera, la vida te empuja a probar, fallar y probar de nuevo. Esta tensión puede sentirse contradictoria pero no lo es — tus períodos de retiro son donde integras las lecciones de tus experimentos. Tu sombra es la autocrítica ante los "errores": en tu diseño, los errores son el método, no la excepción.',
    '2/4': 'Tienes dones naturales que compartes a través de relaciones de confianza, sin haberlo planeado. Tu red social es el canal de tu propósito, pero necesitas también tiempo de retiro genuino para no agotarte. Las personas de confianza reconocen lo que tienes para dar antes de que tú mismo lo declares. El reto es que las relaciones estables son fundamentales — cuando hay demasiada rotación de personas en tu vida, pierdes el hilo de dónde y cómo aportas tu valor real.',
    '3/1': 'Aprendes por experiencia directa — especialmente por lo que no funciona — y construyes sobre eso una base de conocimiento real y aplicado. Tu vida temprana puede estar marcada por muchos intentos, muchos "eso no era lo que pensaba", muchas relaciones o caminos que terminaron. Todo eso tiene un propósito: estás descubriendo con datos de primera mano lo que sí funciona. Tu autoridad más genuina viene de lo que viviste, no de lo que estudiaste. El reto es no cargar con vergüenza por los ciclos que terminaron — cada final fue una puerta a algo más adecuado.',
    '3/2': 'Aprendes por experiencia concreta y necesitas retiro para integrar lo que descubriste. Tus períodos de "salida al mundo" son seguidos de períodos de recogimiento donde procesas en profundidad. Tu maestría real emerge cuando tienes tanto la experiencia vivida como el espacio para mirarla con distancia. Tu sombra es la tendencia a aislarte después de experiencias difíciles — el retiro es necesario, pero el aislamiento prolongado puede convertirse en evitación.',
    '3/3': 'Aprendes completamente por experiencia real — y esa experiencia implica más ciclos de fin y comienzo que para cualquier otro perfil. Tu vida puede parecer caótica desde afuera: muchos proyectos, relaciones, caminos que empiezan y terminan. Desde adentro, cada uno de esos ciclos tiene sentido profundo: estás desarrollando una sabiduría sobre "lo que no funciona" que pocos tienen. El reto mayor es no tomarte los finales como fracasos personales. Eres el experimentador, el que prueba en carne propia para que otros no tengan que hacerlo.',
    '3/4': 'Combinas el aprendizaje por experiencia directa con el canal de las relaciones para expresar ese aprendizaje. Aprendes de la vida — especialmente de lo que no funciona — y luego compartes esas lecciones con tu red cercana. Las relaciones son tanto tu laboratorio como tu plataforma. El reto es que los ciclos de relaciones que terminan pueden doler especialmente — no solo emocionalmente sino porque sientes que perdiste el canal de tu propósito. La red se renueva; la sabiduría que llevas, no.',
    '4/1': 'La Yuxtaposición es el único perfil sin ángulo — tu camino en la vida es fijo, tiene su propia lógica interna. No es que no tengas opciones — es que hay una dirección que es profundamente tuya y cuando estás en ella, fluye; cuando te desvías, hay fricción constante. Tu influencia se ejerce a través de tu red desde una base de conocimiento firme. La clave es confiar en el camino aunque no lo hayas elegido conscientemente — fue diseñado para ti.',
    '4/2': 'Tu propósito se expresa a través de relaciones de confianza y tienes dones naturales que emergen cuando tienes suficiente tiempo propio. Tu red es fundamental — no como estrategia sino como estructura de vida. Las personas cercanas son quienes te abren puertas y quienes mejor ven lo que tienes para dar. Al mismo tiempo, necesitas tiempo solo para que tus dones no se agoten en el dar constante. El reto es que cuando las relaciones centrales cambian, puede sentirse como pérdida de identidad.',
    '4/3': 'Aprendes por experiencia directa y compartes esas lecciones a través de tu red de relaciones. Las crisis que atraviesas no son solo tuyas — son oportunidades de renovar vínculos, reorientar y compartir lo que aprendiste. Tu sombra es que los finales en relaciones pueden sentirse especialmente pesados, porque tu red es el canal de tu propósito. La buena noticia es que tu red se renueva y crece a través de exactamente esas experiencias que temes perder.',
    '4/4': 'Tu propósito se mueve completamente a través de relaciones y redes — no en el sentido emocional sino en el sentido literal de que tu impacto ocurre a través del tejido humano que construyes. Cada relación tiene un propósito aunque no lo veas de inmediato. Tu reto es la estabilidad en esa red: necesitas relaciones sólidas y de largo aliento para que tu influencia se consolide. La rotación constante de personas en tu vida impide que tu propósito cristalice.',
    '5/1': 'El Hereje/Investigador es percibido como alguien que tiene una solución especial — algo que puede resolver lo que otros no pueden. Esto genera proyecciones intensas: la gente espera más de ti de lo que a veces sientes que tienes. Tu base de conocimiento sólida es lo que te protege de que esas proyecciones te abrumen. Tu mayor reto es la reputación: cuando alguien proyecta algo en ti y no lo cumples, la decepción puede ser desproporcionada. Por eso la transparencia y la base real importan tanto.',
    '5/2': 'Cargas con proyecciones intensas del entorno y al mismo tiempo tienes una necesidad profunda de soledad y retiro. Esta combinación puede ser especialmente agotadora: el mundo te llama constantemente mientras tú necesitas espacio para existir. Tu soledad no es evasión — es donde tu verdadero conocimiento se consolida. Cuando gestionas bien esa tensión, lo que ofreces cuando sales tiene una calidad diferente: viene de un lugar genuinamente profundo.',
    '5/3': 'Aprendes en carne propia y el mundo te percibe como referente o solucionador. Puedes sentir que por fuera pareces saber cómo resolver las cosas; por dentro, estás constantemente aprendiendo de lo que no funcionó. Tu autoridad real viene exactamente de esa experiencia directa. La honestidad sobre tu propio proceso es tu mejor protección contra el agotamiento del rol.',
    '5/4': 'Combinas las proyecciones del entorno (la gente espera que tengas algo valioso) con el canal de las relaciones como medio de expresión. Tu propósito se expresa a través de personas de confianza, pero el entorno más amplio también te percibe como alguien que puede resolver o aportar algo especial. Necesitas relaciones estables y una base sólida de conocimiento para no quedar atrapado en las expectativas que otros proyectan en ti.',
    '6/1': 'El Modelo de Rol vive en tres fases distintas. Hasta los ~30 años: experimentación intensa y ensayo-error, donde nada parece durar. De los 30 a los ~50: fase "en el tejado" — observas el mundo desde arriba, procesas todo lo que viviste y empiezas a construir una base profunda. Después de los 50: emerges como modelo de rol genuino — alguien que vivió, procesó y ahora encarna una forma de ser que inspira sin tener que enseñar. Tu mayor autoridad es tu ejemplo de vida, no tus palabras.',
    '6/2': 'Tienes tres fases de vida y dones naturales que emergen sin esfuerzo en la fase madura. La primera fase es experimental e intensa. La segunda es de retiro y observación. La tercera es de emergencia como modelo genuino — un modelo que necesita también espacio propio para seguir recargándose. Tu mayor aporte al mundo no es lo que enseñas sino lo que encarnas. La soledad que necesitas no te hace menos disponible — te hace más auténtico cuando estás presente.',
    '6/3': 'Vives la primera fase del 6 de forma intensa y experimental — ciclos de inicio y fin frecuentes, aprendizaje por lo que no funciona. Esas experiencias, aunque dolorosas, son exactamente lo que construye tu autoridad real en la fase madura. Emerges como modelo de rol no a pesar de lo que viviste, sino gracias a ello. Las personas te buscan porque sienten que no hablas desde la teoría — hablas desde haber estado en el barro.',
    '6/4': 'Expresas tu autoridad de vida a través de relaciones de confianza y redes humanas. En tu fase madura, eres percibido como modelo de rol por las personas cercanas primero — y luego esa influencia se expande. Las relaciones estables son fundamentales: tanto para recibir apoyo como para que tu ejemplo llegue a quienes puede transformar. Tu legado se construye una relación a la vez, durante toda una vida.',
}

HD_AUTHORITY_MEANINGS = {
    'Emocional — Plexo Solar': 'No hay claridad real en el momento de la emoción. Tu proceso funciona en olas: hay un pico de entusiasmo o miedo, luego una baja, y finalmente una neutralidad donde aparece la claridad real. Las decisiones tomadas en el pico de la ola (positiva o negativa) raramente son las mejores. El tiempo no es debilidad — es tu mecanismo de certeza. La pregunta práctica: "¿Cómo me siento con esto después de unos días?" Si la respuesta sigue siendo sí cuando la ola bajó, entonces es sí.',
    'Sacral':                  'Tu cuerpo sabe antes que tu mente. Observa la respuesta visceral — ese "uh-huh" (sí) o "un-un" (no) que surge instantáneamente del centro del cuerpo antes de que la mente intervenga. Esa respuesta no se construye, no se razona, no se explica — se siente. El reto más grande es callar la mente el tiempo suficiente para escucharla. Las preguntas de sí/no en voz alta te ayudan a acceder a ella. Cuando ignoras la respuesta sacral, tarde o temprano aparece la frustración como señal.',
    'Esplénico — Bazo':        'Tu claridad es instantánea e intuitiva — una voz suave que aparece una sola vez y no se repite. No grita ni insiste: llega y se va. Aprender a reconocerla antes de que la mente la tape con razones es el trabajo de toda una vida con esta autoridad. Es la voz del cuerpo en tiempo real: seguridad, salud, intuición. Las decisiones de "esperar para pensar más" a menudo hacen que pierdas la señal más precisa que tienes.',
    'Ego — Corazón':           'Tu brújula real es lo que tu corazón quiere y puede sostener genuinamente. Habla en voz alta sobre lo que decides — escucharte a ti mismo clarifica más que pensar en silencio. La pregunta práctica: "¿Quiero hacer esto? ¿Vale la pena para mí?" Si la respuesta honesta es sí, tienes la energía para sostenerlo. Si hay que convencerte, probablemente no. Esta autoridad requiere honestidad radical contigo mismo sobre lo que realmente quieres, sin disfrazarlo de "deber".',
    'Identidad — G':           'Tu claridad surge en conversación genuina y en el lugar correcto. No decides eficientemente solo — el entorno y las personas de confianza te ayudan a saber qué sientes. Las conversaciones en movimiento (caminar, conducir) a menudo facilitan más claridad que las conversaciones sentado. No estás pidiendo consejo — estás usando la conversación como espejo para escucharte a ti mismo. El lugar donde estás (físicamente, geográficamente) también tiene mucho que decirte.',
    'Lunar — 29 días':         'Cada decisión importante necesita vivirse durante un ciclo lunar completo. No es que no puedas decidir antes — es que los ciclos de la luna te exponen a esa decisión en distintos estados emocionales y energéticos. Lo que sientes el día 1 puede ser completamente distinto del día 15 y del día 29. La consistencia a lo largo del ciclo es tu señal de claridad. Para decisiones cotidianas, no es necesario esperar 29 días — esto aplica a lo que tiene impacto real en tu vida.',
    'Mental — Externo':        'Tu autoridad surge al hablar en voz alta con personas de confianza — no para que te aconsejen, sino para escucharte a ti mismo. El proceso es la conversación, no la conclusión de los demás. Las personas correctas para este proceso son quienes pueden escucharte sin querer dirigirte. Después de la conversación, vuelve a estar contigo mismo y observa qué resonó y qué no. Esta autoridad no significa que otros decidan por ti — significa que necesitas el sonido de tu propia voz reflexionando en presencia de otro para encontrar tu claridad.',
}

HD_NOT_SELF_MEANINGS = {
    'Frustración':          'La frustración es tu señal de que estás usando tu energía sacral en algo que no te genera un "sí" visceral — que decidiste con la cabeza en lugar de responder desde el cuerpo. No es señal de que algo esté "mal" en la situación: es señal de que estás fuera de sincronía con tu propio diseño. Cuando la frustración es crónica, la pregunta no es "¿cómo hago para que esto funcione?" sino "¿respondí genuinamente a esto, o lo decidí con la mente?"',
    'Frustración / Ira':    'La frustración aparece cuando no respondes antes de actuar; la ira cuando actúas sin informar a quienes te rodean. Ambas señales apuntan al mismo lugar: estás operando desde la velocidad mental en lugar de desde la sabiduría de responder Y comunicar. El antídoto no es frenarte — es identificar qué paso se saltó y reintegrarlo. La fricción en el entorno casi siempre tiene una causa directa en la secuencia que se omitió.',
    'Ira':                  'La ira del Manifestador aparece cuando el entorno resiste tus acciones — y generalmente es porque actuaste sin informar antes. No hiciste algo malo: la energía del Manifestador, sin el gesto de informar, genera resistencia automática en quienes te rodean. La ira también aparece cuando sientes que tienes que pedir permiso para hacer lo que sabes que es tuyo hacer. La Paz llega cuando descubres que informar no es pedir permiso — es mover el entorno a tu favor antes de actuar.',
    'Amargura':             'La amargura del Proyector aparece cuando das tu visión o guía sin que nadie te la haya pedido, o cuando te comparas con los Generadores y usas su capacidad de producción como medida de tu valor. La amargura no es resentimiento sin fundamento: es la señal de que estás operando con las reglas del tipo equivocado. Cuando llega la invitación correcta y tu guía es recibida con reconocimiento genuino, la amargura se disuelve sola. La pregunta útil: "¿Me invitaron a esto, o entré sin ser llamado?"',
    'Decepción':            'La decepción del Reflector aparece cuando el entorno en que vives no refleja salud o expansión — y tú, como espejo, lo absorbes como si fuera tuyo. También aparece cuando tomas decisiones importantes sin darte el tiempo del ciclo lunar. La decepción es la señal de que algo en tu entorno necesita cambiar — no tú. Tu primer paso siempre es preguntarte: ¿en qué ambiente estoy viviendo y trabajando? Ese entorno lo cambia casi todo.',
}

HD_SIGNATURE_MEANINGS = {
    'Satisfacción':       'La Satisfacción es la confirmación de que estás respondiendo a lo correcto y siguiendo tu energía sacral genuina. No es euforia ni logro externo — es una sensación tranquila y sostenida de "esto está bien, esto es lo que vine a hacer". Cuando la satisfacción está presente, tu energía se renueva sola. Cuando está ausente, la fatiga no desaparece con descanso — porque no es cansancio físico: es señal de que la dirección necesita ajustarse.',
    'Paz y satisfacción': 'La Paz y la Satisfacción son tus dos firmas simultáneas — la primera te dice que te moviste sin crear fricción innecesaria (informaste antes de actuar); la segunda te confirma que lo que hiciste vino de una respuesta genuina del cuerpo. Cuando ambas están presentes, hay una sensación de que las cosas fluyen: el entorno no resiste, el trabajo no agota. Cuando falta una de las dos, hay información específica sobre qué paso revisar.',
    'Paz':                'La Paz es la firma del Manifestador alineado — la sensación de moverse por el mundo sin fricciones innecesarias, de que las cosas se abren cuando llegas. No es ausencia de desafíos: es la ausencia de la lucha constante que aparece cuando actúas sin informar. La Paz se construye acto a acto, comunicación a comunicación. Cada vez que informas antes de actuar y el entorno responde sin resistencia, eso es la Paz.',
    'Éxito':              'El Éxito del Proyector no es el éxito convencional de producir más. Es la sensación de ser genuinamente reconocido por lo que ves y ofreces — de que tu guía es recibida, de que tu percepción cambia algo real. El Éxito aparece cuando la invitación correcta llega y tú la recibes en lugar de perseguirla. Es la confirmación de que el sistema funciona — cuando esperas en lugar de presionar, lo correcto llega.',
    'Sorpresa':           'La Sorpresa es la firma del Reflector que está en el camino correcto — la capacidad de ser genuinamente asombrado por la vida, de encontrar lo inesperado en lo ordinario. No es shock: es la apertura a lo que la vida ofrece cuando no has decidido de antemano cómo tiene que ser. La Sorpresa es tu indicador de que estás realmente presente y que tu apertura al mundo es un don activo, no una vulnerabilidad.',
}

HD_DEFINITION_MEANINGS = {
    'Indefinido':                'No tienes centros definidos — eres puro espacio de apertura y recepción. Tu don es la flexibilidad y la capacidad de conectar con casi cualquier persona. Tu mayor reto es la identidad: sin la consistencia de los centros definidos, es fácil perderse en lo que absorbes de otros. La práctica más importante es pasar tiempo solo con regularidad para vaciarte de lo que no es tuyo y reconectar con lo que sí lo es. Pregunta clave: "¿Esto que siento o pienso es mío, o lo capté del entorno?"',
    'Definición Simple':         'Tu energía fluye de forma consistente y predecible entre tus centros definidos. Eres esencialmente el mismo en la mayoría de contextos — no necesitas de otros para activarte energéticamente. Tu presencia tiene un efecto de "anclaje" en el entorno: aportas estabilidad y predecibilidad. El reto es la rigidez: cuando la consistencia se convierte en inflexibilidad ante lo nuevo o ante formas de ser muy distintas a la tuya.',
    'Definición Partida':        'Tienes dos circuitos de energía que no están conectados entre sí — dos "modos" de funcionamiento que no siempre se integran fácilmente. Ciertas personas "cierran el puente" entre esos dos circuitos y cuando estás con ellas, te sientes más completo y en flujo. Sin darte cuenta, puedes buscar esa sensación de completitud en relaciones, lo que a veces genera dependencia. El trabajo es aprender a funcionar bien en ambos circuitos por separado, sin necesitar que una persona externa los una.',
    'Definición Partida Triple': 'Tienes tres circuitos de energía separados. Eres energéticamente complejo — distintas personas y contextos activan distintas partes de ti, lo que puede hacerte sentir inconsistente o difícil de entender. Distintas personas "cierran" distintos puentes entre tus circuitos, lo que significa que necesitas diversidad de vínculos para sentirte completo. El reto es encontrar estabilidad propia sin depender de esa activación externa constante.',
    'Definición Cuádruple':      'Tienes cuatro circuitos separados — la definición más compleja. Eres adaptable y multifacético de una forma que puede resultar difícil de comprender incluso para ti mismo. Necesitas una red rica y diversa de relaciones para que todas las partes de tu ser puedan expresarse. El reto más profundo es la coherencia de identidad — saber que aunque te muestres diferente según el contexto, hay un hilo conductor que eres tú.',
}

HD_CENTER_MEANINGS = {
    'Cabeza':      'Centro de la inspiración y la presión mental. Definido: generas preguntas e inspiración de forma consistente y confiable — tu forma de pensar es reconocible. El reto es distinguir qué preguntas son genuinamente tuyas versus cuáles absorbiste del entorno. Indefinido: eres muy sensible a la inspiración ajena y puedes sentir presión para resolver las preguntas de todos. No tienes que responder cada pregunta que surge en tu mente — muchas son del entorno, no tuyas.',
    'Ajna':        'Centro del procesamiento mental y la certeza conceptual. Definido: tienes una forma fija y consistente de analizar y organizar la información — tu perspectiva es reconocible y confiable. El reto es la rigidez: la mente fija puede cerrarse a perspectivas distintas. Indefinido: eres flexible cognitivamente y puedes ver múltiples ángulos, pero también puedes sentir presión para tener certezas que genuinamente no tienes. Tu don es la apertura, no la conclusión — no tienes que saber siempre.',
    'Garganta':    'Centro de la manifestación, la comunicación y la acción. Definido: tienes voz y presencia consistentes — cuando hablas, eres escuchado; cuando actúas, eres notado. El reto es usar el lenguaje con la profundidad que tienes disponible en lugar de hablar por presión. Indefinido: tu expresión varía según el entorno y las personas — adaptabilidad comunicacional que puede resultar en la sensación de no saber cómo expresarte "de verdad". Tu claridad de voz llega cuando estás en el entorno y con las personas correctas.',
    'Identidad':   'Centro del amor propio, la dirección y la identidad del yo. Definido: sabes quién eres aunque el contexto cambie — tienes una brújula interna que te orienta. El reto es la rigidez identitaria: dificultad para soltar versiones pasadas de uno mismo cuando la vida pide evolución. Indefinido: tu sentido del yo es fluido y dependiente del entorno. No estás "perdido": estás diseñado para no tener una identidad fija, y eso es un don de adaptación cuando lo entiendes en lugar de resistirlo.',
    'Corazón':     'Centro de la voluntad, el ego y la capacidad de comprometerse. Definido: tienes fuerza de voluntad consistente y capacidad real de cumplir lo que prometes — cuando decides, la energía para sostenerlo está disponible. El reto es el sobreuso: el Corazón necesita descanso; si te comprometes en exceso, la voluntad se agota. Indefinido: tu fuerza de voluntad varía enormemente. Esto no es pereza ni falta de carácter: es el ritmo de un centro no definido. La clave es comprometerte menos y de forma más intencional.',
    'Plexo Solar': 'Centro emocional. Definido: tienes un ciclo emocional propio — olas de optimismo, profundidad y neutralidad con su propia lógica. Si es tu autoridad: no decidas en el pico ni en el valle — espera la neutralidad. El reto es que el ciclo emocional puede arrastrar a quienes te rodean y en el pico positivo te comprometes a más de lo que el valle puede sostener. Indefinido: absorbes las emociones de otros de forma amplificada. Lo que sientes en grupo puede no ser tuyo. Pregunta constante: "¿Esta emoción es mía o la tomé del entorno?"',
    'Sacral':      'Centro de la fuerza vital, la sexualidad y la capacidad de respuesta. Solo los Generadores y Generadores Manifestantes lo tienen definido. Definido: tienes energía sostenida para el trabajo y la creación — tu batería se recarga durmiendo. Tu respuesta sacral ("uh-huh" o "un-un") es tu guía más confiable. No es mental, no se explica — se siente en el cuerpo. Indefinido: amplificas la energía sacral de quienes lo tienen definido, lo que puede hacerte sentir más energético cerca de Generadores — pero esa no es tu energía real. Necesitas más descanso del que crees.',
    'Bazo':        'Centro de la intuición esplénica, la salud y la supervivencia. Definido: tienes intuición en tiempo real — un saber instantáneo que llega una sola vez, suave, sin repetirse. Aprender a confiar en esa voz antes de que la mente la tape con razones es el trabajo de toda una vida. El reto es que la seguridad de este centro puede llevarte a quedarte en situaciones que ya no son buenas para ti. Indefinido: eres sensible a la salud y el bienestar del entorno. Tu intuición funciona — pero necesita silencio para escucharla.',
    'Raíz':        'Centro de la presión adrenal, el estrés y el impulso que nos mueve a actuar. Definido: tienes un ritmo consistente para manejar la presión — no te desestabiliza fácilmente y tienes energía de "fundamento" bajo condiciones que agotan a otros. El reto es el sobre-empuje: la presión adrenal puede mantenerte en modo de urgencia constante aunque no haya emergencia real. Indefinido: absorbes la presión del entorno de forma amplificada. En contextos de alta presión, puedes sentirte urgido a actuar — pero la urgencia no es tuya. Pregunta clave: "¿Es real esta urgencia, o la tomé del ambiente?"',
}

HD_CHANNEL_MEANINGS = {
    '64–47': 'El Canal de la Abstracción conecta la presión de tener preguntas sin respuesta inmediata (Puerta 64) con la capacidad de eventualmente encontrar sentido en la confusión (Puerta 47). Quien tiene este canal vive con una mente que procesa el pasado buscando patrones — entendiendo la vida hacia atrás, no hacia adelante. La presión mental es real y constante. No necesitas tener la respuesta ahora: el proceso de búsqueda tiene sentido propio, y la comprensión llega en su tiempo.',
    '61–24': 'El Canal del Conocimiento conecta la presión de la inspiración profunda y el misterio (Puerta 61) con el procesamiento repetitivo hasta que emerge comprensión (Puerta 24). Quien tiene este canal tiene momentos de profunda inspiración seguidos de períodos de rumia hasta que el insight aterriza. No fuerces la comprensión — llega cuando llega. Tu mente necesita tiempo y espacio para que lo que "siente" que sabe se vuelva algo que puede articular.',
    '63–4':  'El Canal de la Lógica conecta la duda y el cuestionamiento sistemático (Puerta 63) con la capacidad de formular respuestas (Puerta 4). Es el canal del escepticismo sano — quien lo tiene necesita verificar, probar y cuestionar antes de concluir. No es obstinación: es el proceso de construir certeza real sobre bases sólidas. Tu mente no acepta respuestas sin fundamento — y eso es una fortaleza, aunque a veces resulte agotador.',
    '17–62': 'El Canal de la Aceptación conecta las opiniones y puntos de vista (Puerta 17) con la comunicación precisa de los detalles (Puerta 62). Quien tiene este canal tiene una mente que formula perspectivas claras y las puede articular con detalle y evidencia. El reto: compartir opiniones sin esperar que sean recibidas como verdad absoluta — son puntos de vista, no hechos. La humildad intelectual es la práctica de este canal.',
    '43–23': 'El Canal del Estructuralismo conecta la intuición individual profunda (Puerta 43) con la capacidad de comunicarla de forma que otros entiendan (Puerta 23). Quien lo tiene recibe insights únicos, a veces geniales, que son difíciles de explicar. El timing es fundamental: compartir estos insights cuando el entorno está listo para recibirlos, no antes. Dicho en el momento equivocado, lo más brillante puede sonar extraño.',
    '11–56': 'El Canal de la Curiosidad conecta las ideas y la imaginación (Puerta 11) con la estimulación y el storytelling (Puerta 56). Es el canal del narrador nato — quien lo tiene aprende y estimula a través de historias, metáforas y la capacidad de conectar ideas de formas inesperadas. Tu contribución es inspirar, no concluir. La curiosidad no necesita resolver — necesita compartir el viaje del descubrimiento.',
    '31–7':  'El Canal del Liderazgo Colectivo conecta la influencia del líder (Puerta 31) con el rol orientador del yo en el colectivo (Puerta 7). Es uno de los canales más directamente relacionados con el liderazgo en grupos. Quien lo tiene tiene influencia natural sobre el colectivo y la capacidad de orientar a otros hacia el futuro. La clave es que ese liderazgo funciona cuando es reconocido y pedido — no cuando se auto-proclama.',
    '8–1':   'El Canal de la Inspiración conecta la contribución única al colectivo (Puerta 8) con la expresión creativa individual (Puerta 1). Es el canal del artista y el contribuidor genuino — quien lo tiene tiene algo único para aportar al mundo a través de su expresión creativa. El impacto viene de ser completamente auténtico, no de encajar. Lo que más temes mostrar porque parece "demasiado tuyo" es exactamente lo que más valor tiene.',
    '33–13': 'El Canal del Contemplativo conecta la retirada y la privacidad (Puerta 33) con la escucha y la memoria del yo (Puerta 13). Quien lo tiene guarda los secretos del mundo — la gente se acerca a contarte cosas sin saber bien por qué. También tienes la capacidad de procesar y archivar experiencia colectiva. La retirada periódica no es opcional: es donde integras todo lo que escuchaste y guardaste.',
    '20–10': 'El Canal del Despertar conecta el momento presente y la acción (Puerta 20) con el amor propio y la conducta auténtica (Puerta 10). Es el canal de quien "camina su habla" — cuya presencia en el ahora y cuya autenticidad de comportamiento son la enseñanza en sí misma. No hace falta decir nada: el ser lo dice todo. Tu mayor influencia viene de cómo vives, no de lo que proclamas.',
    '20–34': 'El Canal Poderoso y Ocupado conecta el momento presente (Puerta 20) con el poder puro de la energía sacral (Puerta 34). Es el canal del Generador Manifestante más directo — energía sostenida que se manifiesta en acción inmediata. Quien lo tiene necesita moverse, hacer, crear de forma continua. La inacción es genuinamente incómoda. Tu cuerpo habla a través del movimiento — cuando estás activo con lo correcto, todo fluye.',
    '21–45': 'El Canal del Dinero conecta el control de los recursos (Puerta 21) con el liderazgo y la distribución de recursos del colectivo (Puerta 45). Es el canal de quien maneja y distribuye recursos para el bien del grupo — tiene instinto para el dinero, los materiales y cómo usarlos eficientemente. El reto es el control excesivo: la mano apretada puede impedir el flujo que este canal está diseñado para crear.',
    '16–48': 'El Canal del Talento conecta el entusiasmo y las habilidades (Puerta 16) con la profundidad de conocimiento (Puerta 48). Es el canal del maestro de oficio — alguien que se sumerge profundo en algo hasta dominarlo completamente, y luego lo comparte con entusiasmo genuino. La inseguridad de "no saber suficiente" es parte del proceso, no un obstáculo. La profundidad que buscas llegará con el tiempo y la práctica.',
    '12–22': 'El Canal de la Apertura Social conecta la cautela en la expresión (Puerta 12) con la apertura emocional y la gracia (Puerta 22). Quien lo tiene tiene momentos de profunda apertura comunicativa y momentos de completo retiro — y ambos son necesarios. Su forma de comunicar tiene una calidad emocional única cuando el timing es correcto. No todo momento es el momento: cuando esperas el momento correcto, lo que dices tiene un impacto completamente diferente.',
    '35–36': 'El Canal de la Inquietud conecta el cambio y la búsqueda de nuevas experiencias (Puerta 35) con la crisis como catalizador del crecimiento (Puerta 36). Quien lo tiene tiene hambre genuina de experiencias nuevas — la variedad no es capricho, es necesidad de diseño. A través de sus propias crisis y transiciones, adquieren humanidad y sabiduría para acompañar a otros en los suyos. Tus experiencias límite son tu mayor recurso de empatía.',
    '2–14':  'El Canal de la Abundancia conecta la dirección y la receptividad del yo (Puerta 2) con el poder y el acceso a los recursos (Puerta 14). Quien lo tiene tiene acceso a recursos cuando está alineado con su dirección correcta. El dinero y la abundancia siguen a la alineación, no a la ambición directa. El reto es confiar en ese flujo — cuando fuerzas en la dirección equivocada, los recursos no aparecen aunque trabajes mucho.',
    '5–15':  'El Canal del Ritmo conecta los ritmos fijos y los patrones (Puerta 5) con la modestia y el flujo de la vida (Puerta 15). Quien lo tiene tiene un ritmo de vida propio que puede parecer inflexible pero que, cuando se respeta, abre el flujo. Los horarios erráticos y los cambios de rutina constantes desgastan este canal más que a otros. Tu contribución al colectivo es modelar que hay formas de vivir en sintonía con el ritmo natural.',
    '29–46': 'El Canal del Descubrimiento conecta la perseverancia y el compromiso total (Puerta 29) con la determinación del éxito del cuerpo (Puerta 46). Quien lo tiene encuentra su camino a través del compromiso pleno con las experiencias correctas. El cuerpo como brújula: cuando te comprometes con lo que genuinamente tu cuerpo dice sí, el éxito encuentra su camino. El reto es aprender a reconocer qué compromisos vienen del "sí" del cuerpo y cuáles de la presión mental.',
    '25–51': 'El Canal de la Iniciación conecta la inocencia y el amor universal (Puerta 25) con el coraje ante el shock (Puerta 51). Quien lo tiene tiende a atravesar situaciones de shock o crisis que abren perspectivas espirituales inalcanzables de otro modo. Son iniciados — y a veces iniciadores involuntarios. Las disrupciones en tu vida raramente son accidentales: suelen abrir algo que estaba cerrado y que necesitabas que se abriera.',
    '26–44': 'El Canal de la Transmisión conecta el ego y la memoria del cuerpo (Puerta 26) con el instinto y la alerta del grupo (Puerta 44). Quien lo tiene tiene instinto natural para saber qué necesita el mercado o el grupo — y la capacidad de transmitirlo de forma convincente. Es el canal del vendedor y del comunicador persuasivo. El reto es la integridad: usar ese don de transmisión para lo que verdaderamente vale la pena, no solo para lo que funciona.',
    '37–40': 'El Canal de la Comunidad conecta los pactos y el cuidado de la familia/grupo (Puerta 37) con la soledad y la capacidad de trabajo (Puerta 40). Quien lo tiene vive en la tensión entre el anhelo de comunidad y la necesidad de soledad para recargar. Construye comunidad a través de acuerdos claros y trabajo concreto. Los pactos implícitos no funcionan bien para este canal — lo que no se dice con claridad eventualmente genera resentimiento.',
    '59–6':  'El Canal de la Procreación conecta la intimidad y la disolución de barreras (Puerta 59) con la fricción necesaria para crear algo nuevo (Puerta 6). Quien lo tiene tiene una energía poderosa para crear intimidad — y también para generar la fricción que produce cambio y regeneración. En relaciones, este canal busca profundidad y no tolera la superficialidad por mucho tiempo. La intimidad real, incluyendo sus fricciones, es donde este canal funciona mejor.',
    '19–49': 'El Canal de la Síntesis conecta la sensibilidad ante las necesidades básicas y el querer (Puerta 19) con los principios y la capacidad de revolución (Puerta 49). Quien lo tiene tiene convicciones profundas sobre lo que debe cambiar — especialmente en los principios que rigen la comunidad y los vínculos. La sensibilidad ante la injusticia y el sufrimiento puede ser intensa. Este canal siente fuertemente y puede actuar con decisión cuando los principios son violados.',
    '30–41': 'El Canal del Reconocimiento conecta los deseos y la profundidad emocional (Puerta 30) con la contracción y la imaginación de lo que podría ser (Puerta 41). Es el canal del soñador — quien lo tiene tiene deseos intensos y una capacidad de imaginar vidas y posibilidades que todavía no existen. El reto es aterrizar esa imaginación en experiencia real sin agotarse en el deseo. La vida emocional aquí es rica e intensa — el anhelo puede ser tan fuerte como lo que ya se tiene.',
    '39–55': 'El Canal de la Emoción conecta la provocación y el estímulo (Puerta 39) con el espíritu y las emociones como conciencia (Puerta 55). Es el canal de la melancolía y el espíritu profundo — quien lo tiene tiene una vida emocional intensa con momentos de plenitud espiritual y momentos de profunda soledad. Esa soledad no es vacío: es el espacio donde ocurre la conexión con algo más grande. Este canal tiende a profundizar espiritualmente a través de la experiencia emocional vivida.',
    '27–50': 'El Canal del Cuidado conecta la nutrición y el cuidado instintivo (Puerta 27) con los valores y la ley del grupo (Puerta 50). Quien lo tiene tiene un sentido profundo de responsabilidad hacia la comunidad — cuida, nutre y sostiene los valores que permiten a un grupo funcionar. El reto es no agotarse en el cuidado de otros a costa del propio. Este canal puede sentir el peso de la responsabilidad hacia los demás como si fuera suya de nacimiento — y a veces lo es.',
    '34–57': 'El Canal del Poder Arquetipo conecta el poder puro de la energía sacral (Puerta 34) con la intuición esplénica en tiempo real (Puerta 57). Es el canal del sobreviviente — quien lo tiene tiene una capacidad instintiva y poderosa de actuar en el momento correcto sin necesitar procesamiento mental previo. La intuición y el poder van de la mano: cuando confías en ese instinto corporal, actúas con una precisión que sorprende.',
    '3–60':  'El Canal de la Mutación conecta el orden emergiendo desde el caos (Puerta 3) con la aceptación de los límites y la espera (Puerta 60). Quien lo tiene vive en la tensión entre el impulso de cambio y la resistencia de lo establecido. La mutación real que trae este canal no ocurre siempre ni por voluntad propia — ocurre en momentos específicos, a veces inesperados. Aprender a esperar esos momentos de apertura en lugar de forzar el cambio es el trabajo de este canal.',
    '9–52':  'El Canal de la Concentración conecta el foco en los detalles (Puerta 9) con la quietud y la inmovilidad (Puerta 52). Quien lo tiene tiene una capacidad excepcional de concentración profunda en un solo punto de atención. Pero esa concentración necesita el contexto y el propósito correctos para activarse — no funciona bien en multitasking. La quietud no es pasividad: es la condición que permite el foco total del que este canal es capaz.',
    '42–53': 'El Canal de los Ciclos conecta el crecimiento y la capacidad de completar (Puerta 42) con los nuevos comienzos (Puerta 53). Quien lo tiene tiene una relación especial con los ciclos de inicio, desarrollo y cierre. Necesita terminar lo que empieza para que la energía de nuevo comienzo esté disponible. El cierre limpio es fundamental — los proyectos a medias no solo ocupan espacio mental: impiden genuinamente que algo nuevo entre.',
    '18–58': 'El Canal del Juicio conecta la corrección y el perfeccionamiento (Puerta 18) con la vitalidad y el gozo de vivir (Puerta 58). Quien lo tiene tiene un ojo agudo para lo que puede mejorarse — ve los errores, las ineficiencias y los problemas con claridad natural. El reto es que esa capacidad crítica esté al servicio del bien y no se vuelva hipercrítica o negativa. La pregunta útil: "¿Estoy señalando esto para mejorar, o para desacreditar?"',
    '28–38': 'El Canal de la Lucha conecta el jugador con su destino y el significado de la vida (Puerta 28) con el luchador y la resistencia (Puerta 38). Quien lo tiene tiene una relación profunda con la pregunta por el sentido — no como abstracción filosófica sino como pregunta práctica y urgente: ¿vale la pena luchar por esto? Esa pregunta, bien respondida, los lleva a comprometerse con lo que verdaderamente tiene significado para ellos y a soltar lo que no.',
    '32–54': 'El Canal de la Transformación conecta el instinto de supervivencia y la continuidad (Puerta 32) con la ambición y la transformación a través del ascenso (Puerta 54). Quien lo tiene tiene instinto para reconocer qué proyectos, relaciones o emprendimientos tienen futuro real — y cuáles no. Es el canal del emprendedor con visión de largo plazo. El reto es la presión constante de ascender y mejorar, que puede generar ansiedad cuando el proceso es más lento de lo esperado.',
}

# ── Saju / BaZi ──────────────────────────────────────────────────────────────

SAJU_PILLAR_MEANINGS = {
    'Año':  'Tu energía ancestral y social — la huella del mundo en que naciste y la familia que te formó. Muestra la energía colectiva de tu generación, la relación inicial con el mundo exterior y los patrones heredados de tu linaje. No es el pilar más personal, pero sí el que muestra de dónde vienes. Las fortalezas y los obstáculos de este pilar son frecuentemente los que más tardas en reconocer como propios, porque los absorbiste antes de tener lenguaje para nombrarlos.',
    'Mes':  'Tu pilar vocacional y de propósito — el que más directamente habla de tu forma de trabajar, tus talentos naturales en el ámbito profesional y la dirección de tu energía cuando se trata de crear y aportar. Si el Pilar del Día muestra quién eres, el Pilar del Mes muestra cómo te expresas al mundo. También habla de la relación entre tú y las figuras de cuidado o guía en tu vida.',
    'Día':  'El pilar más importante de los cuatro — tu esencia personal, tu yo más íntimo y auténtico. El Tronco Celeste de este pilar es tu Maestro del Día y define tu naturaleza fundamental: cómo eres en el fondo, cómo procesas la experiencia, cuáles son tus fuerzas innatas y cuáles tus áreas de crecimiento. Todo el sistema Saju/BaZi se interpreta en relación a este pilar. También habla de la relación con la pareja o el compañero de vida.',
    'Hora': 'Tu yo más oculto — las partes de ti que pocas personas ven pero que son profundamente tuyas. Muestra tus miedos más íntimos, tus deseos más profundos y tu relación con los hijos o el legado que deseas dejar. En la segunda mitad de la vida, la energía del Pilar de la Hora se vuelve más activa — es como si lo que estuvo guardado toda la vida empezara a pedir expresión. Quienes conocen este pilar suelen sentir que hay algo en ellos que el mundo raramente ve y que les cuesta integrar con el resto.',
}

SAJU_ELEMENT_MEANINGS = {
    'Madera': 'La Madera representa el impulso de crecimiento, la visión de futuro y la capacidad de expandirse hacia la luz. Como un árbol, se eleva buscando espacio — tiene naturaleza creativa y orientada al propósito. Las personas con mucha energía Madera tienen visión clara, impulso para construir cosas nuevas y una necesidad profunda de crecer. El reto es la rigidez: cuando se siente amenazada, puede tornarse inflexible. La Madera necesita Agua para nutrirse y teme al Metal que la tala — en proyectos y relaciones, busca el apoyo que la nutre y cuida la energía que puede cortarla.',
    'Fuego':  'El Fuego representa la pasión, la transformación y la presencia radiante. Tiene capacidad natural de inspirar, calentar e iluminar los espacios donde está. Las personas con mucha energía Fuego tienen carisma natural, una intensidad que encanta o incomoda, y capacidad de transformar lo que tocan. El reto es la impulsividad y el agotamiento: brilla fuerte pero necesita combustible. Sin Madera que lo alimente, el Fuego se apaga. La práctica del Fuego es aprender a brillar con constancia, no solo en explosiones.',
    'Tierra': 'La Tierra representa la estabilidad, la nutrición y la capacidad de sostener. Como el suelo fértil, crea las condiciones para que todo lo demás crezca. Las personas con mucha energía Tierra tienen una presencia tranquilizadora y un sentido profundo de responsabilidad. El reto es la inercia: puede volverse demasiado pesada, demasiado dependiente de la rutina, y caer en el rol de cuidar a todos sin cuidarse a sí misma. La Tierra necesita moverse y renovarse para no volverse pantano en lugar de suelo fértil.',
    'Metal':  'El Metal representa la precisión, la claridad y la capacidad de separar lo esencial de lo accesorio. La energía Metal tiene un filo — puede cortar limpiamente, encontrar la verdad con claridad y perfeccionar lo que toca. Las personas con mucha energía Metal tienen estándares altos y una capacidad de síntesis extraordinaria. El reto es la frialdad y el perfeccionismo: puede volverse tan exigente que ninguna cosa — incluyendo uno mismo — cumple con los estándares. La práctica del Metal es la excelencia con flexibilidad.',
    'Agua':   'El Agua representa la fluidez, la profundidad, la sabiduría interior y la capacidad de adaptarse sin perder la esencia. Como el agua que encuentra su camino aunque el terreno sea difícil, la energía Agua es resiliente y penetrante. Las personas con mucha energía Agua tienen una vida interior rica y una sabiduría que a veces ellos mismos no reconocen como tal. El reto es la dispersión y el miedo: puede fluir hacia todos lados sin fuerza o estancarse en la profundidad sin moverse. El Agua necesita dirección — un canal que la oriente — para que su poder se exprese sin perderse.',
}

SAJU_DAYMASTER_MEANINGS = {
    'Madera Yang': 'Eres el árbol robusto: directo, con visión clara y capacidad de liderazgo que no necesita proclamarse. Tu fortaleza es la constancia y el crecimiento sostenido. Tu reto es la rigidez — cuando te decides, cuesta mucho hacerte cambiar de dirección incluso cuando el cambio es necesario. También puedes tomar demasiado sobre tus hombros porque tu naturaleza es proveer sombra y estructura para otros. Aprender a delegar y a doblar sin quebrarte es el trabajo de tu vida.',
    'Madera Yin':  'Eres la enredadera flexible: encuentras el camino aunque el terreno sea difícil, rodeando los obstáculos con elegancia. Tu fortaleza es la resiliencia y la inteligencia táctica para moverte en entornos complejos. Tu reto es la dependencia de estructuras externas para sostenerte — la enredadera necesita un árbol o una pared. Cuando esas estructuras desaparecen, puedes sentirte sin suelo. El trabajo de tu vida es desarrollar tu propio eje interno.',
    'Fuego Yang':  'Eres el sol: iluminas todo por igual sin guardarte nada. Tu presencia es poderosa e inmediata — cuando estás, se nota. Tu fortaleza es la generosidad natural y el carisma sin esfuerzo. Tu reto es el exceso de exposición: dar luz a todos puede dejarte sin energía propia. También puedes ser demasiado transparente — mostrarlo todo sin reserva, cuando a veces la profundidad requiere guardar.',
    'Fuego Yin':   'Eres la llama de una vela: iluminas de cerca con una calidez sostenida e íntima. No tienes el drama del sol, pero tienes algo que el sol no tiene: la capacidad de estar presente en la oscuridad más profunda sin apagarte. Tu reto es la vulnerabilidad ante los vientos exteriores — una corriente puede apagar la llama. Necesitas protección, contexto correcto y personas que cuiden tu espacio para brillar de verdad.',
    'Tierra Yang': 'Eres la montaña: ofreces perspectiva, recursos y estabilidad para todos los que te rodean. Tu fortaleza es la capacidad de sostener enormes responsabilidades y de crear estructura donde había caos. Tu reto es la inmovilidad — los cambios profundos de dirección pueden costarte mucho aunque sean necesarios. También puedes cargar con el peso de otros indefinidamente sin reconocer que también necesitas ser sostenido.',
    'Tierra Yin':  'Eres el suelo fértil: receptivo y generador de crecimiento en todo lo que tocas. Tu valor real no siempre se ve de inmediato, pero con el tiempo es innegable. Tu reto es el agotamiento silencioso — dar tanto sin pedir que llega el momento en que el suelo queda sin nutrientes. El trabajo de tu vida es aprender que un suelo bien nutrido da más frutos, y que nutrirse uno mismo no es egoísmo.',
    'Metal Yang':  'Eres el hacha: cortas con precisión lo que necesita ser cortado. Tienes claridad de propósito, capacidad de liderazgo y determinación que impresiona. Tu reto es la dureza sin matices — el hacha no siempre distingue lo que hay que cortar de lo que hay que preservar. La contundencia puede volverse brusquedad; la claridad puede volverse falta de empatía. El trabajo de tu vida es aprender cuándo cortar y cuándo sostener.',
    'Metal Yin':   'Eres la joya pulida: refinada por el tiempo y la presión, con una claridad que brilla con luz propia. Tu fortaleza son tus estándares altos, tu sentido del refinamiento y tu capacidad de ver la belleza donde otros no la ven. Tu reto es que "listo" puede convertirse en un estándar que nunca se alcanza y lo mejor que tienes queda guardado. El trabajo de tu vida es aprender a brillar incluso cuando sientes que todavía te falta pulido.',
    'Agua Yang':   'Eres el océano: contienes profundidades que casi nadie conoce y fuerzas que muy pocos comprenden. Tu fortaleza es la magnitud — sabiduría profunda y capacidad de sostener enormes contradicciones sin resolverlas. Tu reto es la dirección: el océano sin orillas se dispersa. Necesitas estructura y propósito que canalice tu poder — sin eso, la profundidad puede volverse inmovilidad o confusión.',
    'Agua Yin':    'Eres el arroyo tranquilo: llegas siempre a donde vas aunque no hagas ruido. Tu fortaleza es una inteligencia fluida y adaptable que percibe los ambientes con una fineza extraordinaria. Tu reto es la dispersión — el arroyo puede ramificarse tanto que se vuelve charco. El trabajo de tu vida es aprender a fluir con propósito: con la suavidad del agua pero con la claridad del destino.',
}

SAJU_ANIMAL_MEANINGS = {
    'Rata':       'La Rata (Agua) es el primer signo del zodíaco chino — ingenio, adaptabilidad e instinto para las oportunidades. Ves las posibilidades antes que los demás y te mueves con agilidad en entornos complejos. Tu fortaleza es la inteligencia rápida y pragmática, con facilidad natural para acumular recursos y construir redes. Tu reto es la tendencia a guardar demasiado por miedo a la escasez — material o emocionalmente — y a ser demasiado calculador en relaciones, perdiendo la calidez espontánea.',
    'Buey':       'El Buey (Tierra) es el símbolo de la perseverancia y la confiabilidad. Eres lento y constante — pero siempre llegas. No necesitas el aplauso para continuar: tu motor es interno. Tu fortaleza es la capacidad de construir cosas que duran generaciones, con una integridad que genera confianza a largo plazo. Tu reto es la rigidez y la dificultad para delegar o recibir ayuda — prefieres hacer las cosas a tu ritmo antes que adaptarte al de otros.',
    'Tigre':      'El Tigre (Madera) es el símbolo del coraje y el liderazgo natural. Tu presencia es magnética y tu energía hace que las cosas sucedan. Eres audaz, apasionado y no aceptas fácilmente que te digan cómo hacer las cosas. Tu reto es la impulsividad y la dificultad para sostenerte en el proceso largo después del impulso inicial. También puedes ser territorialmente intenso en relaciones — la necesidad de autonomía puede generar roces con quienes quieren acercarse.',
    'Conejo':     'El Conejo (Madera) es el símbolo de la diplomacia y la sensibilidad artística. Tienes un gusto refinado, inteligencia emocional alta e instinto natural para saber qué dice el ambiente sin que nadie lo verbalice. Tu fortaleza es la capacidad de crear espacios donde las personas se sienten seguras y a gusto. Tu reto es la evasión del conflicto — puedes ceder demasiado para mantener la paz, perdiendo tu propia posición, y ser más sensible a la crítica de lo que muestras.',
    'Dragón':     'El Dragón (Tierra) es el signo más poderoso y visionario del zodíaco chino. Tienes ambición natural, creatividad expansiva y una presencia que exige ser reconocida — naciste para dejar huella. Tu fortaleza es la capacidad de visionar e inspirar lo que todavía no existe. Tu reto es el ego y la dificultad para aceptar limitaciones — el Dragón no tolera bien que le digan que no puede. También puedes quemar a las personas cercanas con la intensidad de lo que exiges.',
    'Serpiente':  'La Serpiente (Fuego) es el símbolo de la sabiduría y la intuición profunda. Tienes una inteligencia analítica y estratégica que raramente se muestra de frente — prefieres observar, procesar y actuar en el momento correcto. Eres misterioso por naturaleza, no por cálculo. Tu reto es la desconfianza y la dificultad para soltar el control — la Serpiente no delega fácilmente porque no confía de inmediato. Tu fortaleza es la capacidad de percibir verdades que otros no ven.',
    'Caballo':    'El Caballo (Fuego) es el símbolo de la libertad y la energía ardiente. Tienes una vitalidad que contagia y una resistencia profunda a todo lo que te ata o restringe. Tu fortaleza es esa energía desbordante que, bien dirigida, puede mover proyectos y personas con una fuerza extraordinaria. Tu reto es la dificultad para la constancia y el compromiso a largo plazo — el Caballo necesita sentir que puede moverse, y cuando se siente enjaulado, tarde o temprano rompe el corral.',
    'Cabra':      'La Cabra (Tierra) es el símbolo de la creatividad y la sensibilidad refinada. Tienes un mundo interior rico, sentido estético natural y una capacidad de empatizar que puede ser tanto un don como un peso. Tu fortaleza es crear belleza y traer una calidad humana que enriquece cualquier espacio. Tu reto es la dependencia emocional y la dificultad para sostenerte en entornos duros — la Cabra necesita apoyo y contexto que la nutra para dar lo mejor de sí.',
    'Mono':       'El Mono (Metal) es el símbolo de la versatilidad y el ingenio. Aprendes rápido, resuelves problemas con creatividad y tienes una energía de exploración que pocas personas tienen. Tu fortaleza es esa inteligencia adaptativa que encuentra soluciones donde otros ven muros. Tu reto es la superficialidad por exceso de versatilidad — cuando todo es posible, es fácil no profundizar en nada. La mente que ve todos los ángulos a veces no puede simplemente decidir.',
    'Gallo':      'El Gallo (Metal) es el símbolo de la observación aguda y los altos estándares. Tienes una atención al detalle extraordinaria y un instinto para ver lo que está mal antes de ver lo que está bien. Tu fortaleza es la capacidad de elevar la calidad de lo que tocas a un nivel que otros no alcanzan. Tu reto es la hipercrítica — tanto hacia ti mismo como hacia otros — y ser demasiado pendiente de la imagen y la percepción externa.',
    'Perro':      'El Perro (Tierra) es el símbolo de la lealtad y la justicia. Te quedas cuando otros se van, defiendes a los tuyos y tienes un código moral que no negocia fácilmente. Tu fortaleza es la capacidad de generar confianza profunda — eres la persona que la gente llama cuando las cosas se ponen difíciles. Tu reto es la ansiedad y la vigilancia constante anticipando lo que podría salir mal. La guardia siempre alta puede agotarse con el tiempo.',
    'Cerdo':      'El Cerdo (Agua) es el símbolo de la generosidad, la confianza y la capacidad de disfrutar la vida con plenitud. Tienes una apertura natural hacia los demás y un corazón genuinamente generoso. Tu fortaleza es la capacidad de amar y disfrutar sin complicar lo que es simple — que es exactamente lo que el mundo moderno más necesita. Tu reto es la ingenuidad — confías con facilidad y puedes ser demasiado indulgente, contigo mismo o con los demás.',
}

# ── Human Design — planetas en contexto HD ───────────────────────────────────

HD_PLANET_MEANINGS = {
    'Sol':        'El Sol en HD representa tu propósito de vida — la dirección central que tu energía busca expresar. En la columna de Personalidad (consciente), es quién crees que eres y hacia dónde te orientas conscientemente. En la columna de Diseño (inconsciente), es el propósito más profundo que tu cuerpo y biología llevan — que otros perciben en ti antes de que tú mismo lo veas.',
    'Tierra':     'La Tierra es el opuesto exacto del Sol (180° de distancia) y representa tu anclaje y sustento. En Personalidad, muestra qué te da tierra y estabilidad de forma consciente — qué necesitas para que tu propósito Sol se manifieste. En Diseño, es el anclaje inconsciente que tu cuerpo busca instintivamente, incluso cuando la mente no lo reconoce.',
    'Luna':       'La Luna en HD representa tu ritmo de vida y las necesidades que impulsan tu movimiento cotidiano. En Personalidad, muestra las necesidades que reconoces conscientemente y que buscas nutrir. En Diseño, es el ritmo inconsciente que tu cuerpo sigue — a veces visible solo para quienes te conocen de cerca.',
    'Nodo Norte': 'El Nodo Norte en HD señala el ambiente y el entorno de vida que más te nutre para crecer en la dirección de tu propósito. En Personalidad, es el tipo de ambiente que conscientemente reconoces como expansivo. En Diseño, es el ambiente que tu cuerpo y biología buscan instintivamente, aunque tu mente no siempre lo entienda.',
    'Nodo Sur':   'El Nodo Sur en HD representa los patrones del pasado — lo que llevas de antes, lo que ya conoces profundamente y que a veces se convierte en zona de confort o zona de trampa. En Personalidad, son los patrones que conscientemente identificas en ti. En Diseño, son los condicionamientos más profundos e inconscientes de tu naturaleza.',
    'Mercurio':   'Mercurio en HD señala cómo procesas y comunicas la información de tu diseño. En Personalidad, es tu forma consciente de pensar y expresarte — el estilo comunicativo que reconoces como propio. En Diseño, es la forma en que tu cuerpo procesa y transmite información de forma inconsciente, a menudo expresada sin que te des cuenta.',
    'Venus':      'Venus en HD señala lo que valoras y cómo te relacionas desde tu diseño más profundo. En Personalidad, son los valores y la estética que conscientemente eliges y defiendes. En Diseño, son las atracciones y los valores más instintivos — lo que el cuerpo busca en vínculos y belleza antes de que la mente lo racionalice.',
    'Marte':      'Marte en HD señala cómo diriges tu energía y acción desde tu diseño. En Personalidad, es el impulso consciente que reconoces como tuyo — cómo decides actuar y movilizarte. En Diseño, es la energía instintiva del cuerpo — cómo actúas antes de pensar, lo que el cuerpo hace por impulso propio.',
    'Júpiter':    'Júpiter en HD señala dónde buscas expandirte y qué principios guían tu crecimiento. En Personalidad, es la dirección de expansión que conscientemente reconoces y persigues. En Diseño, es la expansión que ocurre de forma inconsciente — donde la vida te lleva a crecer aunque no lo hayas planificado.',
    'Saturno':    'Saturno en HD señala las estructuras y límites que definen tu diseño. En Personalidad, son los límites y responsabilidades que conscientemente reconoces como necesarios. En Diseño, son las estructuras más profundas e inconscientes que organizan tu cuerpo y tu vida — a menudo sentidas como restricciones hasta que se integran.',
    'Urano':      'Urano en HD señala dónde tu diseño porta un impulso de originalidad y cambio. Como planeta generacional, comparte el signo con millones de personas, pero la puerta específica es única. En Personalidad, es tu impulso consciente de romper esquemas. En Diseño, es la energía disruptiva que tu cuerpo lleva de forma inconsciente.',
    'Neptuno':    'Neptuno en HD señala dónde tu diseño porta una dimensión de espiritualidad, ilusión o trascendencia. Como planeta generacional, es compartido, pero la puerta específica es única. En Personalidad, es tu espiritualidad e ideales conscientes. En Diseño, es la dimensión más etérea e inconsciente de tu naturaleza — aquello que trasciende lo que puedes explicar.',
    'Plutón':     'Plutón en HD señala donde tu diseño porta una energía de transformación profunda generacional. Como planeta generacional, la puerta específica define tu participación única en los patrones de transformación de tu época. En Personalidad, es la transformación que conscientemente reconoces como parte de tu identidad. En Diseño, es la fuerza más profunda e inconsciente que opera en ti.',
}

HD_PERSONALITY_DESIGN_INTRO = 'En Human Design, cada planeta aparece dos veces: en la columna de Personalidad (calipso, lado izquierdo) y en la columna de Diseño (violeta, lado derecho). La Personalidad es lo que puedes ver en ti mismo — tu identidad consciente, lo que piensas que eres. El Diseño es lo que tu cuerpo y biología llevan de forma inconsciente — cómo el mundo te percibe antes de que "hagas" nada. La Puerta y Línea muestran en qué arquetipo específico opera ese planeta en tu chart. La integración de ambas columnas — lo consciente y lo inconsciente — es el trabajo de toda una vida en Human Design.'

# ── Saju — energía breve por Tronco Celeste (para ciclos Daewoon) ─────────────

SAJU_STEM_SHORT = {
    'Madera Yang': 'Período de expansión directa y crecimiento con visión clara — como el árbol que se eleva con determinación. Energía de inicio, liderazgo y construcción hacia adelante.',
    'Madera Yin':  'Período de crecimiento flexible y adaptativo — como la enredadera que encuentra el camino aunque el terreno sea difícil. Energía de resiliencia, persistencia suave y movimiento creativo.',
    'Fuego Yang':  'Período de presencia expansiva, visibilidad y energía radiante — como el sol que ilumina todo a su alrededor. Ciclo de proyección, carisma natural y transformación activa.',
    'Fuego Yin':   'Período de intensidad íntima y profundidad emocional sostenida — como la llama que ilumina de cerca con constancia. Energía de introspección, calidez y conexión profunda.',
    'Tierra Yang': 'Período de consolidación y solidez — como la montaña que ofrece perspectiva y estabilidad. Ciclo para construir bases duraderas, asumir responsabilidades y crear estructuras que soporten el tiempo.',
    'Tierra Yin':  'Período de receptividad y nutrición — como el suelo fértil que permite que todo crezca. Energía de cuidado, sostén y generación silenciosa de frutos a partir de lo sembrado antes.',
    'Metal Yang':  'Período de claridad y decisión — como el hacha que corta lo que ya no sirve. Ciclo de definición de límites, claridad de propósito y eliminación de lo accesorio para revelar lo esencial.',
    'Metal Yin':   'Período de refinamiento y pulido — como la joya que madura bajo presión. Energía de perfeccionamiento, excelencia y consolidación de lo que se ha construido con esfuerzo.',
    'Agua Yang':   'Período de profundidad y fuerza interna — como el océano cuyo poder no siempre es visible desde la superficie. Ciclo de sabiduría emergente, magnitud interior y recursos profundos.',
    'Agua Yin':    'Período de fluidez y adaptación sabia — como el arroyo que llega siempre a donde va sin hacer ruido. Energía de movimiento suave pero constante, introspección y sabiduría que fluye sin esfuerzo.',
}
